- lsm-tree.cabal
- src/Data/Map/Range.hs
- test/map-range-test.hs
To be used in model implementation
> Add rangeLookup implementation for Data.Map

- lsm-tree.cabal
- src/Database/LSMTree/Model/Common.hs
- test/Main.hs
- test/Test/Database/LSMTree/Model/Common.hs
- Include "not-so-trivial" instance for Word64
This will conflict with #7, but I'll resolve the conflicts whichever is merged first.
> Add tests for SomeSerialisationConstraint 

- cabal.project
- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- test/Main.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/Op.hs
- test/Test/Util/Orphans.hs
> Set up infrastructure for lockstep-style testing

- .github/workflows/haskell.yml
I'll remove required GHA jobs that are blocking this PR once I get an approval
> Run Windows and MacOS jobs only on select GHC versions

- lsm-tree.cabal
- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTestQLS.hs
- prototypes/Test.hs
along with a QLS test.
Still to do: shape tests and covering pathalogical small cases.
> Add a prototype of scheduled merges

- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTestQLS.hs
- prototypes/Test.hs
How I love code formatters, especially enforcing them in CI.
> Fix some minor issues on main

- .github/workflows/haskell.yml
> Run build jobs even if formatting checks fail

- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- ~Linear lookup for now~ bisecting
- ~Doesn't return blob references yet~, BlobRefs are returned as well
I'm not sure what to do with single-key page lookups, i.e. what kind of API we should have. Please suggest.
> Add first version of rawPageEntry

- bloomfilter/Data/BloomFilter.hs
- bloomfilter/Data/BloomFilter/Mutable.hs
- bloomfilter/Data/BloomFilter/Mutable/Internal.hs
- bloomfilter/Data/BloomFilter/Util.hs
- lsm-tree.cabal
... size is rounded up to next 64 bits though.
> Relax bloomfilter to allow non-power-of-2 sizes

- src/Database/LSMTree/Internal/Run/BloomFilter.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- test/Test/Database/LSMTree/Internal/Run/Construction.hs
> Incremental, in-memory run construction

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Run/FsPaths.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Run/Mutable.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/utils/Database/LSMTree/Generators.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- test/Main.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/Run/Construction.hs
- test/Test/Database/LSMTree/Model/Monoidal.hs
- test/Test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Util/Orphans.hs
First sketch, let me know if this should be in a different file or something major seems off.
Still depends on #59 to be merged first. The scope of the PR is a bit smaller than the work item. Serialisation of the index and filter has not been implemented, so this just creates empty files for them.
> Write out run from write buffers

- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Run/FsPaths.hs
- src/Database/LSMTree/Internal/Run/Mutable.hs
- test/Test/Database/LSMTree/Internal/Run.hs
> Write checksum file during run construction

- doc/format-run.md
- lsm-tree.cabal
- src/Database/LSMTree/Internal/BitMath.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Run/Index/Compact/Construction.hs
- src/utils/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Run/Index/Compact.hs
~~Depends on #107, but~~ ready to review.
> add (de)serialisation for CompactIndex

- doc/format-run.md
- src/Database/LSMTree/Internal/BloomFilter.hs
- Make length field 64bit (for the future)
- Encode endianess in the version tag
> Change bloomfilter serialization format

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/ByteString.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Run/FsPaths.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Run/Index/Compact/Construction.hs
- src/Database/LSMTree/Internal/Run/Mutable.hs
- src/Database/LSMTree/Internal/Serialise/RawBytes.hs
- src/utils/Database/LSMTree/Generators.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/Run/Construction.hs
- test/Test/Database/LSMTree/Internal/Run/Index/Compact.hs
~~Depends on #108.~~
Tests pass, ~~but there are a few small TODOs and I'll look into reading the `ShortByteString` more efficiently~~ (done).
> Implement run (de)serialisation

- cabal.project
- lsm-tree.cabal
> Use released crc32c-0.2.0

- .github/workflows/haskell.yml
- .hlint.yaml
(but let's first see that job fails)
> Fix HLint again

- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Run/Mutable.hs
See the haddock documentation for the function in the code.
> Add addLargeSerialisedKeyOp

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/Range.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/ModelIO/Class.hs
- test/Test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Util/Orphans.hs
> Add the `Run` type to the fields of `BlobRef`

- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
All the internals deal with serialised representations
> Monomorphise the write buffer

- src/Database/LSMTree/Internal.hs
This does not include a plan for how to handle concurrency for table-specific state, like the write buffer, levels/runs, and the cache. My intention is to flesh that out separately
> More concurrency in open/close functions for `Session` and `TableHandle`

- bench/macro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/RawBytes.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Normal.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
These changes are a preamble for #242. This PR is intended to be read commit by commit
> Refactorings related to `RunFsPaths` (and other paths)

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Util/Orphans.hs
It might make sense to pull more parts of the table handle outside of the `RWVar` and sum type.
> Implement table updates by inserting into write buffer

- doc/format-run.md
This turns the ordinary-index documentation stub into the first version of the full documentation.
> Add documentation of the ordinary index

- src/Database/LSMTree/Internal/Vector.hs
This will ultimately resolve #252.
> Add binary search function for vectors

- bench/macro/lsm-tree-bench-wp8.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
Due diligence for improving the QLS generators and label functions
As an aside: resolves #138
> QLS test improvements

- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/TempRegistry.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- test/Test/Database/LSMTree/Internal.hs
> Merge runs when levels become full

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- lsm-tree.cabal
- prototypes/FormatPage.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/Normal.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Internal/PageAcc1.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/TempRegistry.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Test/Database/LSMTree/Internal/Entry.hs
- test/Test/Database/LSMTree/Internal/Monkey.hs
> Add more default extensions

- test/Test/Data/Arena.hs
The unsafe test didn't use offset information, that will change soon.
> Change arena unsafe freeze test

- lsm-tree.cabal
- src-monkey/Monkey.hs
> Add monkey bits calculations

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/IndexCompact.hs
- doc/format-run.md
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/RawBytes.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/IndexCompact.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
As a result, #204 also becomes obsolete
> Remove range-finder from the compact index

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/Monoidal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/Monoidal.hs
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Main.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Model/Monoidal.hs
- test/Test/Database/LSMTree/Model/Normal.hs
- test/Test/Database/LSMTree/Monoidal.hs
A few TODOs left I want to get back to (input welcome!), otherwise ready.
> Prepare monoidal table API

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- blockio-api/src/System/FS/BlockIO/API.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/CRC32C.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
> Use `hAdvise` for reading and writing runs

- CONTRIBUTING.md
I just added a few lines with example code formatting invocations.
> Added example invocations of project's code formatting policy

- bench/micro/Bench/Database/LSMTree/Monoidal.hs
Just removing some unnecessary code
> Small fix in monoidal benchmarks

- .github/CODEOWNERS
May I please share in the ownership of this code?
> Adding myself as a 'code owner'

- src/Database/LSMTree/Internal/Chunk.hs
- src/Database/LSMTree/Internal/IndexOrdinaryAcc.hs
This replaces all uses of `STRef` by uses of `PrimVar` in the implementation of the ordinary index and general-purpose chunk handling. This should give a slight performance gain while not making the code less comprehensible.
> Switch from `STRef` to `PrimVar` for the ordinary index

- .github/workflows/haskell.yml
- blockio-api/src-linux/System/FS/BlockIO/Async.hs
- blockio-api/src-linux/System/FS/BlockIO/Internal.hs
- blockio-api/src-macos/System/FS/BlockIO/Internal.hs
- blockio-api/src-windows/System/FS/BlockIO/Internal.hs
- blockio-api/src/System/FS/BlockIO/API.hs
- blockio-api/src/System/FS/BlockIO/Serial.hs
- blockio-api/test/Main.hs
- blockio-sim/src/System/FS/BlockIO/Sim.hs
- cabal.project
- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- test/Test/Control/Concurrent/Class/MonadSTM/RWVar.hs
- test/Test/Database/LSMTree/Internal.hs
> Add file locking to `blockio-api`

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
Defines `Cursor` and implements `newCursor` and `closeCursor`, with a focus on resource management. The next PR will implement `readCursor`.
> Implement cursor type, new, close

- lsm-tree.cabal
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Util/FS.hs
> Fix #350 by properly cleaning up RunBuilders in tests

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
Also add TODO to change the reprentation of closed table handle these should not need to have any `TableContent`.
> Add run number field to TableContent

- .hlint.yaml
- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- test/Main.hs
- test/Test/Database/LSMTree/Normal/Examples.hs
... well, one partial example for now
which doesn't work yet. But I also added a bit of helper Show instances to see what's missing
> Add a test file with examples

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
For now, any pattern match on an `OngoingMerge` will lead to an error. This is safe, since we always step merges to completion immediately.
> Represent `OngoingMerge` in `MergingRunState`

- doc/format-run.md
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/IndexOrdinary.hs
> Include the index type in the index versioning information

- bench/micro/Bench/Database/LSMTree/Normal.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
Pretty simple implementation, probably could still be improved.
> Implement range lookups

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
See the commit messages for descriptions of the changes.
These changes are also in preparation for giving merges a `RefCounter`
> Small refactorings for the `Merge` module

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/PageAcc.hs
`PageAcc` can contain uninitialised memory in the vectors for keys and values, so the `NoThunks` instance should not check those entries.
Note that `resetPageAcc` will reset the number of keys currently stored in the page to 0, even though vectors for keys and values are not cleared. If a thunk is in any of these keys, then our `NoThunks` will not catch that, though this is not likely to lead to a proper memory leak.
> `NoThunks` fix for `PageAcc`

- src-control/Control/RefCount.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Normal/Examples.hs
See individual patches. Separate patches for separate tests.
> Enable support for blobs in various tests

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- doc/format-directory.md
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
@jorisdral had some excellent feedback on PR #386 after it got merged. This PR addresses the review feedback https://github.com/IntersectMBO/lsm-tree/pull/386#pullrequestreview-2321588795. Roughly one patch per comment.
> Followup from PR review on #386

- bench/macro/lsm-tree-bench-wp8.hs
- bench/micro/Bench/Database/LSMTree/Monoidal.hs
- bench/micro/Bench/Database/LSMTree/Normal.hs
- doc/format-directory.md
- doc/format-run.md
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model.hs
- test/Database/LSMTree/Model/IO/Monoidal.hs
- test/Database/LSMTree/Model/IO/Normal.hs
- test/Database/LSMTree/Model/Session.hs
- test/Database/LSMTree/Model/Table.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Monkey.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/DL.hs
- test/Test/Util/Orphans.hs
- test/Test/Util/TypeFamilyWrappers.hs
> Rename `TableHandle` to `Table`

- lsm-tree.cabal
- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTest.hs
- prototypes/ScheduledMergesTestQLS.hs
- test/lsm-prototypes-tests.hs
Just a few small refactorings and tweaks, partly in preparation of table union support in the prototype. Probably best reviewed by looking at the individual commits.
> Prototype improvements, support mupsert

- bench/macro/lsm-tree-bench-lookups.hs
- bench/macro/lsm-tree-bench-wp8.hs
- bench/macro/rocksdb-bench-wp8.hs
- bloomfilter/src/Data/BloomFilter/Calc.hs
- bloomfilter/src/Data/BloomFilter/Easy.hs
- bloomfilter/src/Data/BloomFilter/Hash.hs
- src-mcg/MCG.hs
- src-monkey/Monkey.hs
- src/Data/Map/Range.hs
- src/Database/LSMTree/Internal/BloomFilterQuery2.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Internal/PageAcc1.hs
- src/Database/LSMTree/Internal/RawOverflowPage.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/WriteBufferWriter.hs
- test/Test/Database/LSMTree/Internal/Chunk.hs
- test/Test/Database/LSMTree/Internal/Index/Ordinary.hs
- test/Test/Database/LSMTree/Internal/Vector/Growing.hs
- test/map-range-test.hs
It messes with syntax highlighting in GitHub and VSCode
> Do not put `::` on a newline

- src/Database/LSMTree/Internal.hs
`thEnv` identifiers are an artifact from the time that `Table` was called `TableHandle`
> Rename `thEnv` to `tEnv`

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Snapshot.hs
This feature is described in the `format-directory.md` document, but we were not doing it yet in the implementation.
> Renumber run and write buffer files starting from 0 in snapshots

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
The first commit is from #538, so maybe that should be merged first.
> Implement MergeUnion merges

- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
> fix: validate checksums in openWriteBuffer

- src-extras/Database/LSMTree/Extras/Generators.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
Previously, the default generator for `RawBytes` had a tendency to generate small blocks of bytes. The reason was that the length of an underlying buffer could be at most the size parameter but the generated block of bytes constituted only a slice of the buffer. This pull request resolves this issue by allowing the length of the final slice to range up to the size parameter.
Furthermore, this pull request fixes an issue in the tests of transitivity of serialized-key equality and antisymmetry of serialized-key order. The previous implementations of these tests were supposed to work with a fixed, small size parameter, but they invoked the `mapSize` function for each particular test case and thus with keys already chosen instead of invoking it for the entire properties. This issue probably …
> Remove bias from generation of `RawBytes` values

- test/Test/Database/LSMTree/Internal/Chunk.hs
- test/Test/Database/LSMTree/Internal/Vector/Growing.hs
> Turn more private API documentation into Haddock comments

- src/Database/LSMTree/Internal/MergingRun.hs
The merging run finalise was closing input runs before aborting the ongoing merge. When nothing else was holding the input runs open (like the levels cache) then this was resulting in trying to delete the run files while the run readers (in the merge) still had their own open file handles for the same files. This resulted in test failures with the MockFS and would have also failed on Windows filesystems (which do not allow deleting files where there are still open file handles).
> Fix errors on table close with ongoing merges

- test/Test/Database/LSMTree/Internal/Index/Ordinary.hs
> Complement tests of ordinary-index serialization

- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Util/Arbitrary.hs
General improvements. Some things are split out of #592.
Best reviewed commit by commit. The commit messages include test output to show their changes' impact.
> Improvements to generators and shrinkers

- test/Test/Database/LSMTree/StateMachine.hs
And some miscellaneous QLS tagger / generator improvements
> QLS: add `SupplyPortionOfDebt`

- src/Database/LSMTree/Internal.hs
This PR adds `doesSnapshotExist` so the user doesn't have to do ``(snap `elem`) <$> listSnapshots session``.
> feat: export doesSnapshotExist

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/IncomingRun.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Snapshot.hs
Some suggestions that came up while reviewing #608 after it was already merged
> Miscellaneous changes for `IncomingRun`

- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
Updating `Arbitrary` instances of the `SnapMergingTree` and it's recursive sub components. The `arbitrary` generator now creates less large arbitrary values. Conversely, the `shrink` function now explicitly locates and prunes leaf nodes in a `SnapMergingTree` in order to more quickly to converge to minimal counterexample cases.
> Better `SnapMergingTree` Arbitrary instance(s)

- lsm-tree.cabal
For the package description to make sense, this depends on #653, which is still marked WIP due to a few small pending fixes to the error types. Furthermore, this PR leaves a few TODOs that do not have clear answers yet. However, I believe it can be merged in its current state.
> doc: add package description

- scripts/generate-readme.hs
- scripts/pre-commit.sh
* fix: remove cabal-docspec from pre-commit
* fix: add generate-readme to pre-commit
* fix: add  echo to generate-readme
> fix: update pre-commit script

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Cursor.hs
- src/Database/LSMTree/Internal/Index/CompactAcc.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Readers.hs
- src/Database/LSMTree/Simple.hs
- test/Database/LSMTree/Model/Session.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Readers.hs
- test/Test/Database/LSMTree/StateMachine.hs
Lockstep tests pass, but it could use an additional unit test, maybe based on the one in #670.
Some small TODOs, but I think we can leave them for now.
> Consider union level in cursors.

- doc/final-report/integration-notes.md
@geo2a these might be of interest to you
> Add integration notes

- README.md
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Range.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
> fix(docs): process feedback on #701

- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Internal/Types.hs
> A `SerialiseKey` instance for `Void`

- bench/macro/utxo-bench.hs
Previously, the `run` command of the benchmark executable had two flags: `--pipelined` and `--lookup-only`. The value of the second flag had no effect if `--pipelined` was passed to the executable. Now there is a new `--mode` option that can be set to `Sequential`, `Pipelined`, or `LookupOnly`. `Sequential` is the name for what previously was the default mode of the `run` command.
Also: add an update-only mode
> `utxo-bench`: introduce a new `RunMode` option
