IntersectMBO/lsm-tree

- lsm-tree.cabal
- src/Database/LSMTree/Model/Normal.hs
- src/Database/LSMTree/Normal.hs
- test/Main.hs
- test/Test/Database/LSMTree/Model/Normal.hs
Notes:
- Deserialisation must always succeed. Otherwise we'll need to add
`Maybe`s and/or "deserialisation failed" constructors in return types.
(`Maybe` could also be replaced with exceptions in IO interface, is
that the plan?)
- Signature of `retrieveBlobs` doesnt' allow to return "NotFound".
While it's true that BlobRefs are constructed by the library, so there
can be an invariant that blobrefs are always valid,
there *are no* mechanism to prevent trying retriving blob refs from a
*wrong* table.
In the model BlobRef always carries the original (serialised) data,
so it cannot fail.
- The implementation adds few instances for testing purposes:
- Eq, Show, IsList (Table k v blob)
- Eq, Show on LookupResult etc. auxiliary types.
> Model normal

- src/Database/LSMTree/Monoidal.hs
- Export Range constructors
- Export mupserts
- Change Monoid v to SomeUpdateConstraint v mergeTables would probably need SomeSerialisationConstraint v as well, but that change wouldn't be a "typo" fix.
> Fix typos in monoidal interface

- lsm-tree.cabal
- src/Database/LSMTree/Model/Common.hs
- src/Database/LSMTree/Model/Monoidal.hs
- src/Database/LSMTree/Model/Normal.hs
- test/Main.hs
- test/Test/Database/LSMTree/Model/Monoidal.hs
- test/Test/Database/LSMTree/Model/Normal.hs
It's almost the same as normal model (unsurprisingly).
I chose to use merge :: v -> v -> v as the only method of SomeUpdateConstraint.
An alternative is to require SomeSerialisationConstraint as superclass,
and adding an additional method
```haskell
mergeSerialised :: Proxy v -> BS.ByteString -> BS.ByteString -> BS.ByteString
mergeSerialised _ x y = serialise (merge (deserialise x) (deserialise y))
```
with a requirement that specifialised definition should behave as default implementation
`mergeTables` requires SomeSerialisationConstraint (to do the merge).
> Model monoid

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Model/Normal/Session.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
Adds a model that does snapshot/table handle administration within a single session. It is built on top of `Database.LSMTree.Model.Normal`. 
Also includes some small changes to the `Normal` and `Monoidal` APIs.
> Model for lockstep tests

- .stylish-haskell.yaml
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Normal.hs
In particular, discuss snapshots and duplicates: durability and persistent data structures.
> Add miscelaneous haddock doc improvements to the normal API

- lsm-tree.cabal
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/ModelIO/Class.hs
- test/Test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Util/Orphans.hs
As Arbitrary Updates already insert blobs,
we get a bit of blob lookup testing out of this.
> Add lookupsWithBlobs and use that in tests

- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
The table handle should already know its session,
and not having to duplicate the information will only help the code to be correct, as you wouldn't be able to try to snapshot table handle in the wrong session.
> Remove session argument from `snapshot`

- lsm-tree.cabal
- test/Database/LSMTree/Model/Monoidal.hs
- test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Database/LSMTree/ModelIO/Session.hs
- test/Main.hs
- test/Test/Database/LSMTree/ModelIO/Class.hs
- test/Test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Test/Database/LSMTree/ModelIO/Monoidal/Class.hs
- test/Test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Util/Orphans.hs
Builds on top of #26  and #27.
First commit (Copy&paste&tweak ...) is straight-forward.
Second commit adds monoidal specific tests (mupdate and mergeTables)
> Monoidal IO model

- lsm-tree.cabal
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
Other, somewhat related changes:
* Add some TODOs in code
* Generate statemachine actions for two distinct key-value-blob types instead of just one, which should trigger more interesting error cases
* Add `showRealResponse` implementations
> Match ModelIO model with pure model in statemachine tests

- lsm-tree.cabal
- test/kmerge-test.hs
The binary-tree recursive two-way merge is quite fast (but less so for 5 inputs vs. 8 inputs):
eight
sortConcat:    OK (0.25s)
63.2 μs ± 3.8 μs
twoWayMerge:   OK (0.41s)
48.7 μs ± 1.6 μs
twoWayMerge2:  OK (0.15s)
40.0 μs ± 3.1 μs
heapKWayMerge: OK (0.28s)
133  μs ±  11 μs
five
sortConcat:    OK (0.28s)
33.7 μs ± 1.4 μs
twoWayMerge:   OK (0.16s)
20.7 μs ± 1.7 μs
twoWayMerge2:  OK (0.15s)
20.1 μs ± 1.9 μs
heapKWayMerge: OK (0.13s)
65.9 μs ± 5.3 μs
That will be time to beat.
> Add simple k-merge implementations, tests and benchmarks

- bench/micro/Bench/Database/LSMTree/Internal/Run/BloomFilter.hs
- bench/micro/Bench/Database/LSMTree/Internal/Run/Index/Compact.hs
- lsm-tree.cabal
- src/utils/Database/LSMTree/Generators.hs
We were using `Word64`s in the benchmarks, but I changed that to `UTxOKey`s (i.e., `Word256`s) to better simulate real workloads
> Modelled UTxO key for benchmarks and tests

- lsm-tree.cabal
- src-kmerge/KMerge/Heap.hs
- src-kmerge/KMerge/LoserTree.hs
- test/kmerge-test.hs
It seems that we need both the SPECIALIZE pragmas, and -fspecialize-aggressively.
We really need to have both PrimMonad and Ord dictionaries to go away, otherwise loserTreeMerge will be ten times slower.
eight
sortConcat:       OK (0.13s)
63.0 μs ± 5.8 μs
twoWayMerge:      OK (0.20s)
48.4 μs ± 3.3 μs
twoWayMerge2:     OK (0.17s)
39.9 μs ± 3.1 μs
heapKWayMerge:    OK (0.15s)
147  μs ±  13 μs
loserTreeMerge:   OK (0.20s)
52.0 μs ± 3.1 μs
five
sortConcat:       OK (0.14s)
33.0 μs ± 3.2 μs
twoWayMerge:      OK (0.17s)
20.6 μs ± 1.3 μs
twoWayMerge2:     OK (0.16s)
19.2 μs ± 1.5 μs
heapKWayMerge:    OK (0.56s)
67.3 μs ± 3.2 μs
loserTreeMerge:   OK (0.24s)
28.1 μs ± 1.9 μs
> Add a MutableLoserTree implementation

- doc/format-directory.md
- doc/format-page.md
- doc/format-run.md
- lsm-tree.cabal
- prototypes/FormatPage.hs
- prototypes/Test.hs
Covering the outline for all three documents:
* `format-directory.md`: covering the overall LSM directory format
* `format-run.md`: covering the LSM file-run format
* `format-page.md`: covering the LSM file-run _page_ format
And filling in most of the details for the page format documentation.
Also, add a reference implementation and test for the page format.
Covers encoding/decoding and calculating the expected page size
while accumuating key/operation pairs. Includes tests for the usual
round trip properties, and checking size and offset calculations.
This should be the basis for high performance (de)serialisation and
intra-page lookup implementations.
> Initial versions of file format docs and reference impl for page format

- doc/format-page.md
Little bit of code that I tested with:
```haskell
f q = let q' = q .&. ((1 `shiftL` 5) - 1) 
in  (q, shiftR q 5, q' `shiftL` 1, q' `shiftL` 1 + 1)
```
> Specify format of 2-bit operation types in a page

- .github/workflows/haskell.yml
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Serialise.hs
Resolves:
* https://github.com/input-output-hk/lsm-tree/pull/38#discussion_r1432675545
* https://github.com/input-output-hk/lsm-tree/pull/38#discussion_r1432683685
> Fix bit slicing on big-endian systems, drop `ghc-8.10.7`

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
Other stuff may need `Entry` type (e.g. rawpage lookup would/could return it as well).
> Move Entry to its own module

- bench/micro/Bench/Database/LSMTree/Internal/Integration.hs
Otherwise `--list` doesn't work.
I'm surprised that filtering works, i.e. that `criterion` makes proper environments *before* figuring out what to do. `tasty(-bench)` doesn't do so IIRC, i.e. expensive environments are not built if aren't needed.
> Benchmark tree building shouldn't access environment variables

- bench/micro/Bench/Database/LSMTree/Internal/RawPage.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- prototypes/FormatPage.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/RawPage.hs
Benchmark results on my machine look like:
```
benchmarking Bench.Database.LSMTree.Internal.RawPage/missing
time                 104.7 ns   (100.8 ns .. 109.5 ns)
variance introduced by outliers: 78% (severely inflated)
benchmarking Bench.Database.LSMTree.Internal.RawPage/existing-head
time                 266.0 ns   (264.0 ns .. 269.2 ns)
benchmarking Bench.Database.LSMTree.Internal.RawPage/existing-last
time                 288.4 ns   (271.6 ns .. 304.0 ns)
```
looking up the first or last element is virtually the same,
as it should be when using bisecting.
missing being faster than existing element is explainable by the
overhead of actually looking up all the other associated data
(in the generated benchmark input both first and last elements have blobref)
And the algorithmic …
> rawPageEntry micro benchmark

- lsm-tree.cabal
- prototypes/FormatPage.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Serialise.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Run/Construction.hs
This incremental page construction algorithm is a "dumb" algorithm in the sense that it takes keys, operations and possibly blob references as inputs, and accumulates them until a disk page can be filled with the accumulated inputs.  
A builder is provided for serialising pages, but we don't fix the output representation of serialisation yet
Serialisation of the accumulated page is tested against the `FormatPage` prototype.
Incremental, in-memory run construction that uses this page construction will follow in a separate PR
> Incremental, in-memory page construction

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
A nice result of this is that we can go from `SerialisedKey` to the `RawPage`-style keys and back without copying the raw bytes. However, copying is still necessary if the `RawPage`-style key comes from a reusable buffer
> Make `SerialisedKey` sliceable

- doc/format-run.md
* Reorder components to allow incremental writes, with CRC calculations
* Add the LTP bit array
* Put sizes at the end to simplify reading
> Tweaks to the file format spec for the compact index

- bench/micro/Bench/Database/LSMTree/Internal/Integration.hs
- bench/micro/Bench/Database/LSMTree/Internal/Run/BloomFilter.hs
- bench/micro/Bench/Database/LSMTree/Internal/Run/Index/Compact.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Internal/Serialise/RawBytes.hs
- src/utils/Database/LSMTree/Generators.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/Run/Construction.hs
- test/Test/Database/LSMTree/Internal/Run/Index/Compact.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
- test/Test/Util/Orphans.hs
Update serialisation primitives for values and blobs. Also did some refactoring of the code to put it into separate modules:
* `D.L.I.Serialise`: intended for internal use, with newtype wrappers for extra safety
* `D.L.I.Serialise.Class`: intended for the public API. I didn't swap out the `SomeSerialisationConstraint` class yet, because that would further inflate the diff, so I'll do it in a follow-up PR.
* `D.L.I.Serialise.RawBytes`: intended mainly for internal use (like bit-slicing), but since `RawBytes` is the target/source type for serialisation/deserialisation, the type is also re-exported from `Class`
> Serialise class and type for values

- bench/micro/Bench/Database/LSMTree/Internal/Integration.hs
- src/Database/LSMTree/Internal/Integration.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/utils/Database/LSMTree/Generators.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- test/Test/Database/LSMTree/Internal/Run/Index/Compact.hs
Changed `prepLookups` to return a flat list instead of a list of lists. Also, added some newtypes like `PageSpan` and `PageNo`, and removed an indirection from the compact index `search` code.
I compared benchmarks before and after the change, using a fixed seed for the `prepLookups` micro-benchmark. I only benchmarked the default configuration with only positive lookups, because it exercises the most code (i.e., one bloom query and index search for each key-run combination).I also look at the allocations vs. iterations regression.
On 9020d6fe2870e7b137387d821fbc22aa7f71db1e:
```
benchmarking Bench.Database.LSMTree.Internal.Integration/prepLookups for a single run/default, ? actual pages/Bloomfilter query
time                 23.48 ms   (23.23 ms .. 23.67 ms)
1.000 R²   (0.999 R² .. 1.000 …
```
> Minor optimisations for `prepLookups`

- .github/workflows/documentation.yml
- .github/workflows/haskell.yml
- cabal.project
Also: update index-states and update versions for GHC, Cabal, `stylish-haskell`, `cabal-fmt`
> Cache dependencies even if `cabal build` or `cabal test` fails

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Lookup.hs
It's probably useful to have a module that is dedicated just to lookups
> Rename Integration module to Lookup module

- bench/micro/Bench/Database/LSMTree/Internal/RawPage.hs
- doc/format-page.md
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/Run/Construction.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/Run.hs
Previously the rawPageEntry was designed to cover the case where everything fit onto a single page (though it actually worked and was tested for cases where it overflowed into immediately subsequent memory, provided the value end offset remained within 16bits).
Now the renamed rawPageLookup can return either LookupEntryNormal or LookupEntryOverflow. In the latter case it returns the value prefix and it also returns the length of the trailing suffix that needs to be fetched from other subsequent pages.
This means there's no pre-condition on rawPageLookup that it not be a single-entry page.
Update the tests correspondingly.
> Change RawPage lookup to handle overflow case

- lsm-tree.cabal
- test/kmerge-test.hs
I get the following results (but also look at the comparison counts please):
```
bench
eight
sortConcat:       OK (0.26s)
62.5 μs ± 3.3 μs
listMerge:        OK (0.18s)
43.7 μs ± 2.9 μs
treeMerge:        OK (0.15s)
34.7 μs ± 2.8 μs
heapMerge:        OK (0.80s)
96.8 μs ± 3.0 μs
loserTreeMerge:   OK (0.13s)
29.4 μs ± 2.8 μs
mutHeapMerge:     OK (0.21s)
24.8 μs ± 2.1 μs
seven
sortConcat:       OK (0.20s)
47.7 μs ± 3.3 μs
listMerge:        OK (0.14s)
33.9 μs ± 3.0 μs
treeMerge:        OK (0.46s)
27.6 μs ± 2.5 μs
heapMerge:        OK (0.17s)
80.4 μs ± 6.5 μs
loserTreeMerge:   OK (0.21s)
24.6 μs ± 1.4 μs
mutHeapMerge:     OK (0.34s)
20.7 μs ± 921 ns
five
sortConcat:       OK (0.91s)
27.8 μs ± 733 ns
listMerge:        OK (0.14s)
16.8 μs ± 1.6 μs
treeMerge:        OK (0.13s)
15.4 μs ± 1.4 μs …
```
> Add benchmarks for skewed k-way merge

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Run/Construction.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Run/Index/Compact/Construction.hs
- src/Database/LSMTree/Internal/Run/Mutable.hs
- test/Test/Database/LSMTree/Internal/Run/Index/Compact.hs
Small refactorings and fixes that fell out of my in-progress work on serialisation. The only significant change in behaviour comes from changing the length of the range finder (and the corresponding search code).
Might be best reviewed commit by commit.
> Preparations for compact index (de)serialisation

- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Internal/Serialise/RawBytes.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
As the module is import *both* qualified and unqualified, I went ahead and removed/renamed (++), concat and take, as I spend an hour wondering what's wrong with ++.
> Add HasCallStack to RawBytes.unsafeFromRawBytes

- lsm-tree.cabal
- src/Database/LSMTree/Internal/BitMath.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Util/RawPage.hs
The failing test output would look something like
Helps to figure out which bytes are wrong a lot easier.
> Rawpage test comparison

- lsm-tree.cabal
- src/utils/Database/LSMTree/Generators.hs
- test/Main.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Serialise.hs
- test/Test/Util/QuickCheck.hs
Roundtrip test for the in-memory parts: construct a run incrementally from key/value/blob data, then perform lookups on the resulting run (using in-memory raw pages, not actual on-disk pages).
> Test for in-memory run construction and lookups

- bench/macro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- bench/macro/Main.hs
- lsm-tree.cabal
With a setup resembling the LSM siutaion of many filters, in which we look up the same key.
Also add an initial version of a bulk lookup for the same key in many filters. This initial version just shares the hashing, but optimised ones using memory prefetching are also possible.
> Add a macrobenchmark of bloom filter lookup

- lsm-tree.cabal
- src/utils/Database/LSMTree/Util/Orphans.hs
From
```
Benchmarking baseline ... 
(This is the cost of just computing the keys.)
Finished.
Time total:        4.93 seconds
Alloc net per key: 4736.00 bytes
```
to
```
Benchmarking baseline ... 
(This is the cost of just computing the keys.)
Finished.
Time total:        0.12 seconds
Alloc net per key: 48.00 bytes
```
> Optimise SerialiseKey Word256

- bloomfilter/Data/BloomFilter.hs
```
Benchmarking elemCheapHashes ...
(this is the simple one-by-one lookup, less the cost of computing and hashing the keys)
Finished.
Time total:        39.04 seconds
Alloc total:       1.20e11 bytes
Time net:          33.14 seconds
Alloc net:         0.00 bytes
Time net per key:  1.33e-6 seconds
Alloc net per key: 0.00 bytes
```
Notice: `Alloc net per key: 0.00 bytes`
GHC doesn't see that `elemCheapHashes` would benefit from worker-wrapper, until we add a bang. So we do.
(No need to allocate `CheapHashes` if you are goint to evaluate them right away).
> Add bangs to elemCheapHashes

- bench/macro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- bloomfilter/Data/BloomFilter.hs
- bloomfilter/Data/BloomFilter/BitVec64.hs
- bloomfilter/Data/BloomFilter/Easy.hs
- bloomfilter/Data/BloomFilter/Hash.hs
- bloomfilter/Data/BloomFilter/Mutable.hs
- bloomfilter/Data/BloomFilter/Mutable/Internal.hs
- bloomfilter/Data/BloomFilter/Util.hs
- src/Database/LSMTree/Internal/BloomFilter.hs
- src/utils/Database/LSMTree/Extras.hs
- test/Test/Database/LSMTree/Internal/BloomFilter.hs
We need to be more careful with remainder operations, we do them on unsigned Word64s.
I limit the size of bloomfilter to 2^48; which is hopefully enough.
Now the elemCheapHashes is *slower*, this is expected: modulus on 64 bit words is more expensive.
Before
```
Benchmarking baseline ...
(This is the cost of just computing the keys.)
Finished.
Time total:        0.12 seconds
Alloc total:       1.20e9 bytes
Time net:          0.12 seconds
Alloc net:         1.20e9 bytes
Time net per key:  4.89e-9 seconds
Alloc net per key: 48.00 bytes
Benchmarking makeCheapHashes ...
(This includes the cost of hashing the keys, less the cost of computing the keys)
Finished.
Time total:        0.34 seconds
Alloc total:       1.20e9 bytes
Time net:          0.22 seconds
Alloc net:         -752.00 bytes
Time …
```
> Make type Hash = Word64

- .github/workflows/haskell.yml
- README.md
- cabal.project
- fs-api-blockio/src-linux/System/FS/BlockIO/Async.hs
- fs-api-blockio/src-linux/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src-macos/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src-windows/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src/System/FS/BlockIO/API.hs
- fs-api-blockio/src/System/FS/BlockIO/IO.hs
- fs-api-blockio/src/System/FS/BlockIO/Serial.hs
- fs-api-blockio/test/Main.hs
- lsm-tree.cabal
~~Now that we depend on `blockio-uring`, we have to drop GHA for Windows and MacOS for now, until we have an alternative for those platforms~~ EDIT: no longer the case, we are implementing an alternative API for Windows and MacOS
> Add blockio-uring dependency

- .github/workflows/haskell.yml
- lsm-tree.cabal
I'm curious whether CI will pass if we dont avx2
> Dont mavx2 on OSX

- cabal.project
Update the `blockio-uring` s-r-p to include the bugfix from https://github.com/well-typed/blockio-uring/pull/10, and disable the `serialblockio` flag in `cabal.project`
> Fix hanging test suite `fs-api-blockio-test`

- lsm-tree.cabal
- test/kmerge-test.hs
benchmarks take non-deterministic time to run.
`tasty-bench` test methodology is crappy, as on noisy machine it easily uses time up to the timeout. Maybe we should only use `criterion` (which is crappy too, but at least it has strict time limits)
> Move kmerge benchmarks into non-test-suite component

- cabal.project
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
At least in CI, so we get better error checking of low level operations.
Yes currently this exposes some failures that we ought to fix.
> Use -fcheck-prim-bounds in lsm-tree, primitive & vector

- .hlint.yaml
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Assertions.hs
- src/Database/LSMTree/Internal/BloomFilter.hs
- src/Database/LSMTree/Internal/PageAcc1.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/Run/Index/Compact.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/Database/LSMTree/Internal/Serialise/RawBytes.hs
- src/Database/LSMTree/Internal/Vector.hs
- src/utils/Database/LSMTree/Generators.hs
- src/utils/Database/LSMTree/Util/Orphans.hs
- Add `mkPrimVector` smart constructor.
- Use hlint to prohibit `Vector` constructor usage, but it's fine to use it in pattern matches
If this is good approach, we probably should add HLint job to CI. (It doesn't complain about anything in `src/` atm).
> Mk prim vector

- lsm-tree.cabal
- prototypes/FormatPage.hs
- src/Database/LSMTree/Internal/Assertions.hs
- src/Database/LSMTree/Internal/BitMath.hs
- src/Database/LSMTree/Internal/PageAcc1.hs
- src/Database/LSMTree/Internal/RawOverflowPage.hs
- src/Database/LSMTree/Internal/Serialise/RawBytes.hs
- src/utils/Database/LSMTree/Generators.hs
- test/Main.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/PageAcc1.hs
- test/Test/Database/LSMTree/Internal/RawOverflowPage.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Util/RawPage.hs
This is preparation for integrating the `MPageAcc` type in run construction.
We add a `RawOverflowPage` type and tests, and we change `PageAcc1.singletonPage` to return `(RawPage, [RawOverflowPage])` rather than `(RawPage, RawBytes)`.
> Add a RawOverflowPage type and start to use it

- prototypes/ScheduledMerges.hs
The constraint is redundant when assertions are optimised away.
> Remove redundant HasCallStack constraint

- bench/macro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- cabal.project
- cabal.project.debug
Also move debug part of cabal.project into separate import, so it's easier to disable.
Add a CPP, so we know if debug stuff is on.
> Hardcode expected allocations per key in bloom macro bench

- cabal.project
- fs-api-blockio/src-linux/System/FS/BlockIO/Async.hs
- fs-api-blockio/src/System/FS/BlockIO/API.hs
- fs-api-blockio/src/System/FS/BlockIO/Serial.hs
- fs-api-blockio/test/Main.hs
- lsm-tree.cabal
Update `blockio-uring` to the latest version, and adapt the `fs-api-blockio` code to use vectors instead of lists
> `submitIO` using vectors

- lsm-tree.cabal
... which is bundled with GHC-9.8
> Allow bytestring-0.12

- .github/workflows/haskell.yml
Without a fixed index-state and with only one unique cache name before, GHA is likely to rebuild dependencies from scratch each time we run the formatting jobs. Fixing the index-state and using the value in the primary key of the GHA caches, we won't rebuild dependencies superfluously any longer, and we have control over when we want to build newer versions of our formatting tools, or update their dependencies.
> Fix the index-state for formatting jobs in GHA

- src/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/Run.hs
As mentioned in https://github.com/IntersectMBO/lsm-tree/pull/166#discussion_r1562569738, this is a similar change as for `RunBuilder`. No other types have these prefixes. Since we're refactoring a few things at the moment, it seems like a good opportunity to make this change.
> Remove lsm- prefix of Run record fields

- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/BloomFilter.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- test/Test/Database/LSMTree/Common.hs
- test/Test/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
For consistency. The Acc suffix already indicates mutability, so no need to have a prefix.
> Rename MPageAcc to PageAcc

- src-extras/Database/LSMTree/Extras.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Generators.hs
Not particularly elegant, but improves the chance of hitting interesting cases until we have a more principled approach.
Output:
```
Test.Database.LSMTree.Generators
key/op pairs
prop_distributionKOps: OK (2.19s)
+++ OK, passed 800 tests:
57.2% any k/op is large
32.5% has key with >2 collisions
23.4% >10% of keys collide
k/op is large (19686 in total):
95.205% False
4.795% True
k/op sizes (19686 in total):
38.535% 16 <= n < 64
22.803% 64 <= n < 256
13.629% 256 <= n < 1024
10.556% 4 <= n < 16
9.728% 1024 <= n < 4096
4.750% 4096 <= n < 16384
key counts (18044 in total):
95.140% 1
2.455% 2
1.313% 3
0.643% 4
0.255% 5
0.127% 6
0.044% 7
0.017% 8
0.006% 10
key sizes (19686 in total):
52.845% 16 <= n < 64
32.871% 4 <= n < 16
14.284% 64 <= n < 256
value sizes (18128 in total):
25.359% 16 <= n < 64 …
```
> improve Arbitrary instances for serialised keys and values

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Serialise/Class.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Serialise/Class.hs
There was one bug in the instance for Word64. Now there is just one issue left: We require that instances should preserve the ordering of their un-serialised representation, but [`ByteArray` doesn't use lexicographic ordering](https://www.stackage.org/haddock/lts-22.7/base-4.18.2.0/src/Data.Array.Byte.html#line-212). So either:
1. the instance shouldn't exist (one could use a newtype wrapper or `RawBytes` directly, if we want to expose that)
2. ~~we do some hack with serialising the length as the first byte, but that's ugly and slow~~
3. we drop the requirement on instances
I feel like option 3 might be possible, in which case it seems preferable. I think the original reasoning was about the ordering in the write buffer, but we already use `SerialisedKey` there, so I think we're good?
> Add property tests for instances of SerialiseKey and SerialiseValue

- .github/workflows/documentation.yml
- .github/workflows/haskell.yml
Let's `apt-get update` fail. We really care that the `apt-get install` succeeds.
> apt-get update workaround

- src/Database/LSMTree/Internal/Normal.hs
This is needed for benchmarks (measuring the overhead of operation generation).
> Add NFData (Normal.Update v blob) instance

- bench/micro/Bench/Database/LSMTree/Internal/RawPage.hs
- prototypes/FormatPage.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/PageAcc1.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
We use the reference implementation as a source of truth in tests of our implementation of code that works with the page format. The changes here are intended to reduce the difference between the reference implementation and real implementation, to make the tests simpler and better.
Previously, the model/prototype allowed an optional blob ref with every operation. Our real implementation however only allows a blob to be associated with an insert. We now think the latter makes more sense, so we now tighten the model to do the same:
```    
data Operation = Insert  Value (Maybe BlobRef)
| Mupsert Value
| Delete
```
This also makes some of the tests simpler, since they match up more directly.
> Tighten the representation of operations in the model

- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/Orphans.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/Monoidal.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
First draft, I still want to:
- factor some things out of this benchmark and the `Lookup` one it is based on
- think about which input distributions we really want to measure
- properly look at the results
<details>
<summary>benchmark output</summary>
```
benchmarking Bench.Database.LSMTree.Internal.WriteBuffer/word64-2k/insert
time                 687.7 μs   (686.0 μs .. 689.1 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 690.1 μs   (688.9 μs .. 692.4 μs)
std dev              5.597 μs   (3.378 μs .. 9.407 μs)
allocated:           1.000 R²   (1.000 R² .. 1.000 R²)
iters              1276688.340 (1276684.791 .. 1276692.537)
y                  2933.008   (2505.811 .. 3405.795)
benchmarking Bench.Database.LSMTree.Internal.WriteBuffer/word64-2k/flush
time                 427.0 μs …
```
> Add micro benchmark for write buffer

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunFsPaths.hs
- src/Database/LSMTree/Internal/RunReader.hs
The last step of flattening the `Run` hierarchy (and thus concluding #106).
> Move module Run.FsPaths

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunFsPaths.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
I should have done this as part of #200, but just only realised it now.
There is no need for a module re-export and we don't do it anywhere else.
Also, wanting to know the file paths to where a run stores its data breaks the abstraction boundary and is only needed for tests or benchmarks. As such, it's good to be more explicit about importing them.
> Remove re-export of RunFsPaths

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- fs-api-blockio/src-linux/System/FS/BlockIO/Async.hs
- fs-api-blockio/src-linux/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src-macos/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src-windows/System/FS/BlockIO/Internal.hs
- fs-api-blockio/src/System/FS/BlockIO/API.hs
- fs-api-blockio/src/System/FS/BlockIO/IO.hs
- fs-api-blockio/test/Main.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
Otherwise, it's opaque to the user what values are being used. By making the default parameters explicit, the user has full control.
> Make the default `IOCtxParams` explicit

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Random.hs
Output:
<details>
```
benchmarking Bench.Database.LSMTree.Internal.Merge/word64-insert-x2/merge
time                 12.58 ms   (12.50 ms .. 12.66 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 12.52 ms   (12.48 ms .. 12.58 ms)
std dev              128.4 μs   (88.78 μs .. 215.9 μs)
allocated:           1.000 R²   (1.000 R² .. 1.000 R²)
iters              4.496e7    (4.496e7 .. 4.496e7)
y                  -28.758    (-1143.358 .. 1049.724)
benchmarking Bench.Database.LSMTree.Internal.Merge/word64-insert-x4/merge
time                 14.25 ms   (14.20 ms .. 14.29 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 14.21 ms   (14.18 ms .. 14.25 ms)
std dev              78.37 μs   (58.54 μs .. 113.9 μs)
allocated:           1.000 R²   (1.000 R² .. 1.000 R²)
iters …
```
> Micro benchmark for run merging

- .github/workflows/haskell.yml
- bench/macro/rocksdb-bench-wp8.hs
- lsm-tree.cabal
- src-rocksdb/RocksDB.hs
- src-rocksdb/RocksDB/FFI.hs
On my machine
```
% cabal run rocksdb-bench-wp8 -- run  
GlobalOpts {rootDir = "_bench_rocksdb", initialSize = 100000000}
CmdRun (RunOpts {batchCount = 1000, batchSize = 256, check = False, seed = 1337})
Proper run:             11.229 sec
Operations per second: 22798.0 ops
% cabal run rocksdb-bench-wp8 -- run
GlobalOpts {rootDir = "_bench_rocksdb", initialSize = 100000000}
CmdRun (RunOpts {batchCount = 1000, batchSize = 256, check = False, seed = 1337})
Proper run:             11.091 sec
Operations per second: 23082.4 ops
% cabal run rocksdb-bench-wp8 -- run
GlobalOpts {rootDir = "_bench_rocksdb", initialSize = 100000000}
CmdRun (RunOpts {batchCount = 1000, batchSize = 256, check = False, seed = 1337})
Proper run:             11.048 sec
Operations per second: 23171.7 ops
```
Note, the …
> Add rocksdb wrapper, and comparison wp8-like benchmark

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Lookup.hs
This tackles the same thing as #212, but only for the lookup micro-benchmarks.
> More granular micro-benchmark for the IO part of lookups

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
The refactoring I had planned, getting rid of the `IORef Entry` and enabling a few other optimisations.
I realised I had run the benchmarks in #203 using an older GHC version (9.2), so I also included that comparison here.
In terms of allocated bytes per entry:
| benchmark                      | GHC 9.2 | main  | refactor |
|--------------------------------|---------|-------|----------|
| word64-insert-x4               |     899 |   823 |      655 |
| word64-delete-x4               |     750 |   667 |      483 |
| word64-delete-x4-lastlevel     |     452 |   356 |      172 |
| word64-blob-x4                 |   31340 | 31198 |    31030 |
| word64-mupsert-x4              |     899 |   823 |      671 |
| word64-mupsert-collisions-x4   |     723 |   653 |      475 |
| word64-mix-x4 …
> Refactor run merging

- bench/macro/lsm-tree-bench-wp8.hs
- lsm-tree.cabal
- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTestQLS.hs
- src/Database/LSMTree/Internal/Normal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Model/Normal.hs
- test/Test/Database/LSMTree/ModelIO/Class.hs
- test/Test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/Op.hs
- test/Test/Util/Orphans.hs
Most of the changes are mechnical. One TODO I left in the `lsm-tree-bench-wp8` module is that we'd preferably use vectors directly in the generation of batches. I'm first going to ensure that the public API also uses vectors for updates.
> Use vectors in the public API functions for lookups

- test/Test/Database/LSMTree/Internal.hs
If https://github.com/IntersectMBO/lsm-tree/actions/runs/9225657061/job/25383623470#step:15:512 shows up again, then this will show what the unexpected output of the test was.
> Show unexpected outputs in session tests

- prototypes/FormatPage.hs
- src-extras/Database/LSMTree/Extras/ReferenceImpl.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/Internal/PageAcc1.hs
Use new general real/reference conversion functions to help write simpler tests. Also find and fix a bug.
This PR should be read patch by patch. See the descriptions for each patch individually.
This builds on top of #229 but that should be merged first, and then this rebased.
> Extend and simplify tests for PageAcc and PageAcc1

- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal.hs
> Fix `FsResourceAlreadyExist` errors during session restore

- lsm-tree.cabal
- src/Database/LSMTree/Internal/IndexOrdinary.hs
This adds support for the ordinary index apart from serialization.
> Add the core of the ordinary index support

- .gitignore
- scripts/format-cabal-find.sh
- scripts/format-stylish-find.sh
Avoid looking at .hs files under ./dist-newstyle, and all files under ./.git* and ./_bench_*.
This fixes the script (which was failing to parse the .hs files in some dependencies) and makes it faster (looking at fewer files).
> Fix/improve the find script for stylish-haskell

- bench/macro/lsm-tree-bench-wp8.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
Add the pipelined mode to the WP8 benchmark.
This is a bit awkward because to work with the real implementation it requires the duplicate action, which isn't implemented yet. So we can't get performance results for this yet.
I've tested the pipelined mode with the model implementation and that works fine, but I don't want to include that in the benchmark code because it pulls in too many other dependencies.
So to test the pipelined (and sequential) versions I've included a dynamic check that the results are the same as a simple pure reference function. This is enabled by --check. Hopefully the presence of the observation/output doesn't have much of a performance impact when it is disabled. Casual benchmark runs indicated the cost was less than the run-to-run variation.
The PR starts with …
> pipelined mode for WP8 benchmark

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
As discussed in https://github.com/IntersectMBO/lsm-tree/pull/215#discussion_r1608330935.
Perhaps not the ideal use case for quickcheck-lockstep, e.g. not making use of variables, but probably better than not having tests. Will help with ensuring the correctness of future optimisations.
> Add lockstep tests for MergeReaders

- src/Database/LSMTree/Internal.hs
This is in preparation for the temporary implementation of `duplicate`
> Tweak `TableHandleEnv`

- bench/micro/Bench/Database/LSMTree/Internal/IndexCompact.hs
Construction becomes ~5x slower and has ~3.5x more allocated bytes. Search becomes 35x slower, and has 4876x allocations
```
❯ cabal run lsm-tree-micro-bench -- -m pattern non-uniformity --regress allocated:iters
benchmarking Bench.Database.LSMTree.Internal.IndexCompact/non-uniformity/construct appsWithNearDups
time                 191.5 μs   (189.7 μs .. 193.8 μs)
0.999 R²   (0.999 R² .. 1.000 R²)
mean                 190.2 μs   (189.5 μs .. 191.7 μs)
std dev              3.189 μs   (2.175 μs .. 4.562 μs)
allocated:           1.000 R²   (1.000 R² .. 1.000 R²)
iters              907512.241 (907511.284 .. 907513.119)
y                  3005.069   (2605.877 .. 3408.336)
benchmarking Bench.Database.LSMTree.Internal.IndexCompact/non-uniformity/construct appsWithoutNearDups
time …
```
> Micro-benchmark `IndexCompact` with non-uniform UTXO keys

- bench/micro/Bench/Database/LSMTree/Internal/Serialise.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/UTxO.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- test/Test/Database/LSMTree/Internal/Serialise/Class.hs
**Comparing the `Serialise` benchmark before and after #308**
```
Benchmark                                                                before    after
Bench.Database.LSMTree.Internal.Serialise/UTxOKey/serialiseKey           0.593e-8  2.870e-8 +383.88%
Bench.Database.LSMTree.Internal.Serialise/UTxOKey/serialiseKeyRoundtrip  0.734e-8  4.863e-8 +562.07%
Geometric mean                                                           0.660e-8  3.736e-8 +466.00%
```
[before.log](https://github.com/user-attachments/files/16411256/before.log)
[before.csv](https://github.com/user-attachments/files/16411257/before.csv)
[after.log](https://github.com/user-attachments/files/16411258/after.log)
[after.csv](https://github.com/user-attachments/files/16411259/after.csv)
**Comparing the first commit of #306 …
> Change the serialisation of `UTxOKey`

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
~~Depends on #314. Before un-drafting this, I want to make sure all the tests are enabled and run successfully.~~
As a bonus, the `Internal` module now doesn't know anything about the normal/monoidal distinction. We prevent opening a normal snapshot as monoidal through the labels (although we might iterate on the exact design of that).
I haven't touched any of the TODOs from #314 yet, we should first discuss what we want to do there.
The tests all seem to be enabled now, unless I missed something.
> Implement monoidal table API

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Chunk.hs
This adds a general-purpose module for dealing with chunks, which comprises a chunk type and support for chunk production suitable for incremental index serialization.
Note that this pull request does not include tests. These are called for by #297.
> Add general-purpose chunk handling

- bench/micro/Bench/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
The configuration option currently has no effect: the Compact Index is always used.
> Add configuration option for the fence pointer index

- src/Data/Arena.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
Saving allocations and indirections in the lookup code path.
> Two micro-optimisations

- .github/workflows/haskell.yml
- bench/macro/lsm-tree-bench-bloomfilter.hs
- bench/macro/lsm-tree-bench-wp8.hs
- bench/micro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- bench/micro/Bench/Database/LSMTree/Internal/IndexCompact.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- blockio-sim/src/System/FS/BlockIO/Sim.hs
- cabal.project
- lsm-tree.cabal
- prototypes/FormatPage.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/RawPage.hs
- test/Database/LSMTree/Model/Monoidal.hs
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Internal/CRC32C.hs
On my machine, `ghc-9.10` is the default compiler. Hence my first attempt at build the project failed... but barely. I notice that the project could easily build with the newest version of GHC with very minor changes to disambiguate some calls to `foldl'`. This PR adds future-proofing compatibility with GHC 9.10.
> Minor refactoring to add compatability with GHC 9.10

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Chunk.hs
- src/Database/LSMTree/Internal/IndexOrdinaryAcc.hs
This adds support for incremental construction and serialization of ordinary indexes.
Note that the branch of this pull request is currently stacked onto the branch of #296, as it depends on it. Once #296 is merged, I shall rebase the branch of the present pull request onto the then current `main`.
> Add incremental functionality for the ordinary index

- .github/workflows/haskell.yml
- .hlint.yaml
- bench/macro/lsm-tree-bench-bloomfilter.hs
- bench/macro/lsm-tree-bench-lookups.hs
- bench/macro/lsm-tree-bench-wp8.hs
- src-kmerge/KMerge/Heap.hs
- src-kmerge/KMerge/LoserTree.hs
- src/Database/LSMTree/Internal/RawBytes.hs
Our GitHub action for running HLint on the code was previously emitting an alarming warning:
```
Running hlint -j --json -- src/ test/
Warning: Can't find file "MachDeps.h" in directories
src/Database/LSMTree/Internal
.
Asked for by: src/Database/LSMTree/Internal/RawBytes.hs  at line 8 col 1
hlint completed with status code 0
```
The `haskell.yml` workflow file's entry for the HLint action had previously specified only `fail-on: suggestion` whereas this PR increases the failure condition to `fail-on: warning`. This change causes our CI pipeline to have caught and require correcting the previously ignored warning.
Additionally, the PR corrects the warning by conditionally importing the offending file.
> Correcting false positive of HLint passing GitHub workflow

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/Lookup.hs
This PR performs the TODO task of changing the type-synonym `NumPages` to a proper `newtype`.
The `NumPages` is now a `newtype` wrapper of the `Word` data-type, as there cannot ever be a negative number of pages.
Additionally, I added documentation for `NumPages` and corrected a few typos in the module's existing documentation.
> Performing TODO: Create newtype

- lsm-tree.cabal
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Chunk.hs
> Add tests for general-purpose chunk handling

- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Monoidal.hs
- test/Test/Database/LSMTree/Monoidal.hs
We can revisit this once we focus on robustness, including error handling during run merges.
> Remove Totality requirement for ResolveValue

- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTestQLS.hs
Probably easiest to review commit by commit.
I managed to find a few invariants that too tight, or looser than necessary. However, this required adding handwritten tests, as the lockstep test coverage is not great.
The fix for incorrect assumptions violated by 5-way merges (holding back an underfull run) are simply addressed by providing more merge credits, but there are alternatives we can think about afterwards (e.g. #311)
> Tweaks and small fixes to the prototype

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Related to #218
The "Bug report' and "Feature request" templates are the standard ones provided by GitHUb. "Blank issue" is a custom template that can be used when a topic does not fit one of the existing templates.
> Add standard issue templates

- src-kmerge/KMerge/Heap.hs
- src-kmerge/KMerge/LoserTree.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/kmerge-test.hs
Rather than returning a `Maybe a` when creating a new mutable heap from an input list (`[]`), instead require that the input be `NonEmpty` and always be able to return an `a` value in the result tuple. This pushes the check for emptiness one level up in the computational logic, requiring the caller of `newMutableHeap` to have witnessed the non-emptiness of the function's input.
**Type signature change** *(constraints removed for clarity)*:
```
newMutableHeap :: [a]        -> m (MutableHeap (PrimState m) a, Maybe a)
newMutableHeap :: NonEmpty a -> m (MutableHeap (PrimState m) a,       a)
```
> Improving type safety of `KMerge.Heap.newMutableHeap`

- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/Monoidal.hs
- src/Database/LSMTree/Internal/Normal.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/Monoidal.hs
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/Op.hs
- test/Test/Util/Orphans.hs
Defines the public API for cursors. The implementation will follow soon, but I decided to split the work into small PRs, so individual aspects can be reviewed and merged separately. For example, based on this PR, one could already start integrating the new cursor API into the quickcheck-lockstep tests.
I decided to rename RangeLookupResult, since it will be used for cursor reads, too. Generally it is useful for returning entries when their keys are not already known, which is everything except for (point) lookups.
> Define cursor API

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
The `Internal` module is growing rather large, so I am planning on moving functionality related to merge scheduling to a new module in preparation for the implementation of scheduled merges. For that, we first need to move the config types to prevent cyclic dependencies.
> Move table config types to a new module

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- test/Test/Database/LSMTree/Internal.hs
The `Internal` module is growing rather large, this commit moves functionality related to merge scheduling to a new module. This is in preparation for implementing properly scheduled merges.
> Move code for flushes and merges to a new module

- src/Database/LSMTree/Internal/IndexOrdinaryAcc.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Internal/Vector.hs
This pull request adds a function `byteVectorFromPrim`, which converts a value of a primitive type into a primitive vector of bytes that contains the value’s representation. Furthermore, this pull request changes existing code to use this function.
It is expected that `byteVectorFromPrim` will be useful in more places; in particular, the tests for the ordinary index will likely benefit from it. All in all, the conversion from primitive values to byte vectors seems common enough to warrant the introduction of a dedicated function.
> Introduce `byteVectorFromPrim`

- bench/micro/Bench/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
The merge schedule can either be `OneShot` or `Incremental`. Having this configuration option will allow us to test and benchmark the two versions of the merge algorithm separately. We can remove the `OneShot` option later when/if we decide that the incremental version should be the default.
> Add a configuration option for the merge schedule

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
This replaces the reference counting functionality on `Run`s. Other uses, such as adding reference counting to merging runs, will be added later
> Start using the new `RefCounter` datatype

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
We don't need a placeholder value.
This resolves issue in #361
> Remove emptyTableContent

- src/Database/LSMTree/Internal/IndexOrdinary.hs
This changes all identifiers in the ordinary-index implementation that start with `entriesCount` to identifiers that start with `entryCount` instead, as the word before “count” should always be in singular, which is also the rule that has been followed in other parts of the codebase.
> Correct `entriesCount` to `entryCount`

- test/Test/Database/LSMTree/Internal/Chunk.hs
This modifies the import list of the chunk testing module such that `(>>>)` is imported via `Control.Category` instead of `Control.Arrow`, which effectively reduces the number of modules to be imported.
> Tighten the imports of the chunk testing module

- lsm-tree.cabal
- src-control/Control/Concurrent/Class/MonadSTM/RWVar.hs
- src-control/Control/RefCount.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src-kmerge/KMerge/Heap.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Assertions.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/RawOverflowPage.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/UniqCounter.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
This PR adds proper `NoThunks` instances for most of the datatypes in our library as orphans in the `extras` sub-library. *Only* the `StateMachine` tests will now check for `NoThunks`, and the PR includes some fixes for failing `NoThunks` assertions.
> Create proper `NoThunks` instances

- src-control/Control/RefCount.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
The goal is to have a single representation for BlobRefs whether they're from runs or from the write buffer.
The intention is that this representation will also be sufficient to cover BlobRefs for blobs from the write buffer, using an open file handle and a suitable reference count.
So rather than containing a run it contains a file handle and a reference count.
```diff
- blobRefRun   :: !run
+ blobRefFile  :: !h
+ blobRefCount :: {-# UNPACK #-} !(RefCounter m)
``` 
When making a BlobRef for a run, we just take the blob file handle and the run's reference count.
> Change BlobRef representation to not be specific to Run

- src-control/Control/RefCount.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Normal.hs
- test-control/Test/Control/RefCount.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
It is partial because there is no support for BlobRefs in the write buffer yet.
As such it doesn't make a lot of sense to test in this interim state, so this PR does not enable tests for the public API. This can follow once we incorporate WriteBuffer support.
> Partial implementation of retrieveBlobs in the public API

- bench/micro/Bench/Database/LSMTree/Normal.hs
- bench/micro/Main.hs
- lsm-tree.cabal
This benchmark can be used to compare lookups with large values to lookups with the same large value divided into a small value and a blob.
> Simple, comparative micro-benchmark for blob references.

- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
Introduce an internal `WeakBlobRef` type. This is used as the internal representation for the public API `BlobRef` type.
Otherwise internally, `WeakBlobRef` is the weak version and `BlobRef` is the strong one where you have (or are assumed to have) a reference on the file/run whatever.
And then provide utilities for dereferencing a weak ref to get a strong ref. This means we get all the weak refcount stuff in one place (in the `BlobRef` module) and its use in `Database.LSMTree.Internal` becomes quite straightforward and doesn't need access to internal representations.
> Clarify distinction between weak and strong BlobRefs

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
This is a first step towards implementing scheduled merges. As an intermediate solution, we use a 'MutVar' as the mutable reference. Once we implement scheduling properly, this will replaced by a more suitable alternative.
> Put `MergingRunState` into a mutable reference

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
Allows to pass a write buffer into `RunReaders`. This is needed for cursors, which read from all runs and the write buffer.
This requires an additional branch for each entry being read. In the run merge micro benchmark, allocations and run time are unaffected.
> Generalise RunReaders to support write buffers

- lsm-tree.cabal
We've had some discussion in the past about whether (i) we want this as a sublibrary, or whether (ii) we want to include the source files directly in the components that need them. I'd like to revive option (ii), since option (i) degrades my HLS experience due to ambiguity -- I suspect HLS gets confused because a file in the `Extras` hierarchy might be loaded as part of any component that includes the file. It basically means I get no useful HLS feedback as soon as I open an `Extras` file, and it occasionally prevents HLS from giving useful feedback on modules that depend on such an `Extras` module
> Revive the `extras` sublibrary

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
Just a small refactoring. `ReadCtx` previously hard-coded IO despite being used in other parametrised records.
> Add type parameter m to ReadCtx

- bench/micro/Bench/Database/LSMTree/Internal/RawPage.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Internal/RawPage.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/RawPage.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Util/FS.hs
First part of Work Product 12, adding the functionality to start `RunReaders` at an offset.
The new `rawPageFindKey` function has the same performance characteristics as `rawPageLookup` but facilitates starting the `RunReaders` at an give page offset from the returned index. `RunReader.new` now takes an optional offset as an argument.
> Adding functionality to initialise RunReaders at offset

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
Change the `WriteBuffer` to store `BlobSpan` rather than `SerialisedBlob`
This requires some preparatory changes and entails a lot of minor changes elsewhere. Instead of storing blobs in memory in the write buffer itself we now have to write blobs to the `WriteBufferBlobs`, which gets us back `BlobSpans` and then those `BlobSpans` go into the `WriteBuffer`.
This PR should be read patch by patch. The final patch is unfortunately rather long, with only one or two interesting bits. Pay attention to the reference counting of the `WriteBufferBlobs`. I'm not sure how well covered that is by tests (though some tests did fail due to files being left open, and those are fixes). In particular duplication isn't covered well yet.
> store write buffer blobs on disk

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/Monoidal.hs
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Database/LSMTree/ModelIO/Monoidal.hs
- test/Database/LSMTree/ModelIO/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
Makes use of #346 to optionally initialise cursors at an offset. This is exposed in the public API and will be the foundation for range lookups.
> Allow creating cursor at offset

- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
This should now complete the functionality and testing for the blobs feature.
Previous PRs changed the way blobs were managed in the write buffer. This PR does the final wiring between lookups in the write buffer and returning BlobRefs via the public API.
Then it also enables generating blobs and blobrefs in various tests. In particular this includes the state machine tests. Enabling these uncovered a few mismatches between the model and implementation. See issue #392.
It also covers some of the overlap between cursors and blobs: returning blob references from cursors is now enabled and the tests are passing.
There are sill some TODOs that would be nice to do. In particular the way the write buffer is handled during lookup is rather ugly. The use of the write buffer could be properly …
> Enable returning BlobRefs in the API, enable tests, and minor fixes

- src/Database/LSMTree/Internal/IndexOrdinary.hs
This fixes a bug that violated `prop_searchForUnmentionedKeyInRangeWorks`. It also contains a small stylistic improvement in nearby code, which is in line with the style of the fixed code.
> Fix a bug in ordinary index search

- src-control/Control/RefCount.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
In two places, we use `RecursiveDo` to attach a `RefCounter` with finaliser to a `Run`. Because we evaluate the finaliser as much as possible before storing it in the `RefCounter`, we are getting "cyclic evaluation" errors in some cases where we use recursive `do` (i.e., `fixIO`). To prevent these errors from occurring, we instead do not evaluate the finaliser at all before storing it in a `RefCounter`.
> Make the`Refcounter`'s `finaliser` field  less strict.

- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/RunReader.hs
In case `search` was given a key that was smaller than all keys on all pages in the index, then `search` would return `PageSpan 0 0` by default. However, if page 0 contains a large value that overflows into subsequent pages, then `PageSpan 0 0` is not valid because we have to include all the overflow pages as well. Instead, `search` now consults the `LTP` array to ensure that we return a valid page span. In addition, the `search` code has been cleaned up a little, and it's documentation has been improved.
A `TODO` in `RunReader.new` has been addressed, which depended on `search` returning valid page spans.
> Make `IndexCompact.search` return valid page spans in some edge cases

- bench/macro/lsm-tree-bench-wp8.hs
- lsm-tree.cabal
Add a --lookup-only mode to the WP8 benchmark.
Optimise the WP8 benchmark by changing the key extension algorithm. The key extension takes an integer and extends it to a 34 byte key, intended to have a good uniform distribution in the key space. The change is that instead of using a crypto hash (SHA256), use a non-crypto PRNG (StdGen). The latter is much cheaper and allocates less.
Also do a few minor micro-optimisations.
Benchmark for 10,000,000 initial keys, and looking up 8,000 batches of 256 keys. Results on my machine, best of two runs each, before and after.
* Runtime: 27.7s
* IOPs: 74005.0 ops/sec
* Allocated: 13.6 Gb
* Productivity: 98.7%
* Runtime: 25.3s
* IOPs: 80925.3 ops/sec
* Allocated: 2.7 Gb
* Productivity: 99.4%
For 8,000 batches, both before and after `dry-run --check` …
> WP8 benchmark lookup optimisation

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
See the individual patches for more detailed descriptions.
> Refactor write buffer in lookupsIO

- src-extras/Database/LSMTree/Extras/Generators.hs
- test/Test/Database/LSMTree/Internal/Chunk.hs
This makes the type of primitive vectors an instance of `Arbitrary`. The corresponding instance declaration is added to `Database.LSMTree.Extras.Generators`, which previously had only been used for LSM-tree-specific things. If it should be put elsewhere, the reviewer should say so. 🙂
> Add `Arbitrary` instantiation for primitive vectors

- src-control/Control/RefCount.hs
This makes it slightly easier to see where assertions related to reference count invariants fail.
> Give errors in `addReference` and `removeReference` a callstack

- bench/macro/lsm-tree-bench-bloomfilter.hs
- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bloomfilter/src/Data/BloomFilter.hs
- bloomfilter/src/Data/BloomFilter/BitVec64.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/BloomFilterQuery1.hs
- src/Database/LSMTree/Internal/BloomFilterQuery2.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/StrictArray.hs
- src/Database/LSMTree/Internal/Vector.hs
- test/Test/Database/LSMTree/Internal/BloomFilter.hs
- test/Test/Database/LSMTree/Internal/Entry.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Util/QC.hs
For the bloom filter macrobenchmark (on my laptop with 6Mb L3 cache) this is about 2x faster at 25M entries, and about 3x faster at 100M entries.
> bloomfilter bulk query optimisation with memory prefetching

- lsm-tree.cabal
- src/Database/LSMTree/Internal/IndexOrdinary.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/IndexOrdinary.hs
This adds tests for the ordinary index.
Currently, the property `prop_searchForUnmentionedKeyBeyondRangeWorks` tends to discard too many test cases. I will address this and then drop the draft status of this pull request.
> Add tests for the ordinary index

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Monoidal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Util/Orphans.hs
A reasonably large-scale refactoring (of API type signatures) which addresses the numerous TODO annotations stating *"replace by* [`io-classes`](https://hackage.haskell.org/package/io-classes) *constraints for IO simulation"* in order to provide a more general, polymorphic API for users of the `lsm-tree` library. The indirect object to be replaced that the TODO annotation references are the `m ~ IO` constraints found on the same line(s) prefixing the TODO annotation, allowing the post-refactoring functions to abstract over `IO` operations rather than exposing an API which is specialized to `IO`. While most TODO annotations were in the `Database.LSMTree.Internal` module, this PR touches many additional modules. This wide footprint of changes is necessary because the …
> Swapping IO for abstract IO type-classes

- .github/workflows/documentation.yml
This should fix our documentation on github pages, which currently has bad hyperlinks.
> Use `cabal-3.12.1.0` in documentation CI

- blockio-api/test/Main.hs
- blockio-sim/src/System/FS/BlockIO/Sim.hs
- blockio-sim/test/Main.hs
- lsm-tree.cabal
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Util/FS.hs
What's neat is that we can now find out in our `StateMachine` tests whether our implementation is leaking file descriptors!
> Simulate file locks in `blockio-sim`

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
With the imminent implementation of scheduled merges, we have to take special measures against runs being closed under our feet during operations like `lookups`. `lookups` use a `LevelsCache` for quick access to the runs in a table, and it is currently an invariant that the set of runs in this `LevelsCache` is the same as the set of runs that is stored in the `Levels` structure of a table.  With scheduled merges, if an ongoing merge completes, then the completion process will release a number of references to the merge's input runs, so that unused runs are closed in a timely manner. However, if this happens concurrently with a `lookups` operation, then runs could be closed while `lookups` is still using them, leading to exceptions.
The currently proposed solution is to have the …
> Have `LevelsCache`s take references on runs.

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
In addition, the merge now keeps track of the 'MergeState' (instead of just the last `StepResult`), which is used to check even more bad usages of the `Merge` API. Examples are using `complete` before merging was done, or using `complete` on a closed `Merge`.
FYI: our merge algorithm ensures that `Merge`s are only accessed sequentially through the use of a `StrictMVar`. There might be opportunities for more fine-grained concurrency, but for now this *should* be functionally correct
> Give `Merge` a reference counter

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
In some places, we were adding/removing references but not taking into account rollbacks/delays that should be performed when exceptions occur. In particular, correct acquisition and release of write buffer blob files were not guarded by `allocateTemp` and `freeTemp`.
In addition, to make our reference accounting slightly less error prone, we make a few related changes:
* We add new  `addReferenceTableContent` and `removeReferenceTableContent` functions, which replace most occurrences of manually increasing/decreasing reference counts for the components of a  `TableContent`. For example, in `duplicate` and `close` we now use the new functions.
* `newWith` now uses a `TempRegistry`, which fixes a double-free TODO.
* `newWith` now requires a full `TableContent` to be passed in.
> Fix adding/removing references on table content

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
Refactors the usage of `HasFS` and `HasBlockIO` abstractions, by "internalizing" the values within the data-types which require them. This noticeably cleans up the module API interface, removing the requirement of manually passing `HasFS` and `HasBlockIO` values across multiple abstraction layers of the `LSMTree`. The `HasFS` and `HasBlockIO` are now required from the user *only* when creating a new `RunBuilder, rather than required for most functions exposed by a half dozen module's interfaces.
~~*NB: Still needs to be rebased with `main` which will require another sizable chunk of time.*~~
> Refactoring APIs involving HasIO & HasBlockIO

- lsm-tree.cabal
- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Main.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/DL.hs
- test/Test/Util/PrettyProxy.hs
The lockstep improvements are mainly there to make it easier to run counterexamples produced by the state machine tests, which are printed as `DL` expressions.
> How to run a `DL` expression, and some lockstep improvements

- test/Test/Database/LSMTree/Normal/StateMachine.hs
The `TableConfig` arbitrary instance is still quite suboptimal. I've added a TODO to improve it.
> Shrink `TableConfig` in `StateMachine` tests

- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/RunNumber.hs
- src/Database/LSMTree/Internal/Snapshot.hs
The current snapshot format is only loosely established, so we add a more concrete snapshot format, which is more amenable to refactoring. This snapshot format is still temporary -- we will implement snapshots properly in a later package.
#426 is near to being ready, but it is currently still failing some tests related to snapshots. Establishing a snapshot format makes bug-hunting in the snapshot code easier.
> Implement a more proper snapshot format

- lsm-tree.cabal
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Cursor.hs
Instead of splitting the whole module as proposed in #432, we might want to just move more logic out of the `Internal` module (without API types like `Cursor` and `TableHandle`). I also documented that approach in the module description.
> move Cursor read logic into separate module

- test/Database/LSMTree/Model/Normal.hs
- test/Database/LSMTree/Model/Normal/Session.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
Add labels for:
* number of tables
* number of actions per table
* logical size of tables
* per-run number of actions (failing and succeeding)
* label failing actions with the exception
* label interleaving depth on duplicate tables
Initial results for each in each patch.
It's clear from several of these measures that the generation is suboptimal. One idea to improve it is to make the generation more sophisticated by (usually) only generating actions on live tables (or cursors, or existant snapshots). This is however difficult-to-impossible to do with the current `quickcheck-lockstep` package which does not provide a `lookUp` function to the action generation `arbitraryWithVars`. So there's no way to filter vars by their liveness (from looking at the model). It may make sense to extend …
> Add more labels to the quickcheck-lockstep StateMachine tests

- lsm-tree.cabal
- src/Database/LSMTree/Internal/IndexOrdinaryAcc.hs
- src/Database/LSMTree/Internal/Vector/Growing.hs
- test/Test/Database/LSMTree/Internal/IndexOrdinary.hs
So far, incremental construction of an ordinary index required users to provide an upper bound of the number of pages or equivalently the number of keys stored in the index. However, such an upper bound cannot be reliably computed.
This pull request introduces an implementation of “growing vectors” and adapts ordinary-index construction to make use of it. As a result, it is not necessary anymore to provide an upper bound of the number of keys but only an initial size of the key buffer. For performance reasons, it is good for this initial size to be an upper bound of the number of keys, but index construction will also work if it is not.
This pull request does not contain tests for growing vectors. These will be added later by resolving #420.
> Enable ordinary-index building without a page count bound

- src/Database/LSMTree/Internal/Chunk.hs
The module `Database.LSMTree.Internal.Chunk` lacked a description. This pull request adds one.
> Add description to chunk module

- cabal.project
The old commit has disappeared due to a rebase in `quickcheck-lockstep`.
> Hotfix: update `quickcheck-lockstep` commit tag

- .github/workflows/haskell.yml
- cabal.project
- cabal.project.debug
- cabal.project.release
This PR restructures `cabal.project` into `cabal.project.release` and `cabal.project.debug` so that we can switch between release/debug builds from the command line rather than by editing a file, to avoid the need to `git stash/apply` when switching branches, and to enable an entirely programmatic `git bisect` for benchmarks. It also symlinks `cabal.project.debug` to `cabal.project` as the default configuration.
> Restructure `cabal.project` files.

- bench/macro/lsm-tree-bench-bloomfilter.hs
- bench/macro/lsm-tree-bench-lookups.hs
- bench/macro/lsm-tree-bench-wp8.hs
- bench/macro/rocksdb-bench-wp8.hs
Depends on #450. Consistently adds the warning and includes instructions to run in release mode.
> Clarify warning when benchmarking in debug mode

- lsm-tree.cabal
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class/Monoidal.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
If the snapshot versioning scheme is to your liking, then we should probably also make it part of the PR checklist to update version numbers in case there are changes to the snapshot format.
> Define snapshot versioning and metadata

- bench/macro/lsm-tree-bench-wp8.hs
- lsm-tree.cabal
We add a new `measure-batch-latency` flag that, if enabled, produces a file with datapoints about the that can be rendered, for example using `gnuplot`. In sequential mode, the datapoints consist of latency for lookups, and latency for updates separately. In pipelined mode, there are two additional datapoints for the sync latency between threads.
When the flag is disabled, all functions related to latency measurements default to no-ops. These functions are always inlined, and should be optimised away nicely.
> Measure latency for batches of updates and lookups in the WP8 benchmark

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/IndexOrdinary.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Page.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/IndexCompact.hs
- test/Test/Database/LSMTree/Internal/IndexOrdinary.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
This pull request moves `PageNo`, `NumPages`, and `PageSpan` along with the operations associated with them out of `Database.LSMTree.Internal.IndexCompact` and into a new, dedicated module. The reason for this change is that those things are not specific to the compact index, not even to indexes at all. This pull request is not least part of the preparations for making index types selectable.
> Separate utilities related to pages

- .github/workflows/haskell.yml
And make sure to hash all configuration files (like `*.cabal*` and `cabal.project*`) correctly, and include those hahses in the GHA cache names too. We no longer hash put `**` in front of the globs, because that matches on files in `dist-newstyle` as well.
This is a follow-up to #450, which broke uniqueness 
Note that changes to *any* `cabal.project*` file will lead to a changed hash name, but I'd prefer that over the more involved approach of determining exactly which config files are in use by a job, and only hash those. It's also not really a problem if the hash name changes: it just means we store a new cache and the old one at some point gets evicted when it hasn't been used in a while.
> Restore uniqueness of GHA cache names per configuration

- bench/micro/Bench/Database/LSMTree/Normal.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Snapshot.hs
This is a follow-up to #426
The best description of the approach can be found in the code, in the GHC-style note `Note [Credits]`
> Do merge work in batches

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobFile.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Cursor.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/RunReaders.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
PR designed to be reviewed patch by patch.
Overall, this is a refactoring in preparation for changes to the ref counting API. The ref counting change will be about making things follow a model of there being singular references, rather than manipulating raw reference counts. This changes the BlobRef representation so that it follows this style: it now holds a reference to a BlobFile (which is itself a reference counted object). Previously it was more ad-hoc. Also more cleanly separate three kinds of reference: raw, weak and strong.
> Refactor blob refs

- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/IO/Normal.hs
It does not only make sense for monoidal tables, but also for normal ones. Should be straightforward to support.
> Add table union to normal API

- src/Database/LSMTree/Internal/Chunk.hs
- src/Database/LSMTree/Internal/IndexCompact.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/Chunk.hs
- test/Test/Database/LSMTree/Internal/IndexCompact.hs
- test/Test/Database/LSMTree/Internal/IndexOrdinary.hs
This pull request makes the compact index use the `Chunk` type defined in `Database.LSMTree.Internal.Chunk`, which the ordinary index is already using. This paves the way to a common interface for both the ordinary and the compact index.
> Make the different index types use a common chunk type

- .hlint.yaml
- CODEOWNERS
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/Snapshot.hs
And put the snapshot metadata file in there. In addition, compute the checksum for the metadata file and put it in a separate file in the same directory.
> Create a proper directory for each snapshot 

- .stylish-haskell.yaml
- scripts/format-cabal.sh
- scripts/format-stylish.sh
- scripts/pre-commit.sh
Supersedes #461. Turns out Git does not enjoy squashing across merge commits.
> Speed up `scripts/format-stylish.sh`

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/ChecksumHandle.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
This PR:
- Moves `ChecksumHandle` and its core functions to their own module (`Database.LSMTree.Internal.ChecksumHandle`).
- Generalises the helper functions in `RunBuilder` (`writeRawPage`, `writeRawOverflowPages`, `writeBlob`, `copyBlob`, `writeFilter`, `writeIndexHeader`, `writeIndexChunk`, `writeIndexFinal`) to only take the arguments they need, rather than the entire `RunBuilder`.
- Moves those helper functions to the new `ChecksumHandle` module. This enables them to be reused by the `WriteBufferWriter`. (Technically, the latter four are not needed, but it seemed better to generalise and move them for consistency.)
> Move `ChecksumHandle` and its methods into their own module

- bench/micro/Bench/Database/LSMTree/Internal/IndexCompact.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/Index.hs
- src/Database/LSMTree/Internal/IndexCompactAcc.hs
- src/Database/LSMTree/Internal/IndexOrdinaryAcc.hs
- test/Test/Database/LSMTree/Internal/IndexCompact.hs
- test/Test/Database/LSMTree/Internal/IndexOrdinary.hs
This pull request moves `Append` and `append` out of `Database.LSMTree.Internal.IndexCompact`. The reason is that `Append` is not specific to the compact index and `append` will not be either once the class of index types is introduced. The target of this move is a new module for indexes in general, situated in the `extras` package, as only tests and benchmarks are using `Append` and `append`.
> Move general append utilities into general index module

- src/Database/LSMTree/Internal/CRC32C.hs
Just fixing the haddock comment:
```diff
- {- | $checksum-files
+ {- $checksum-files
```
> Fix haddock in CRC32C

- .github/workflows/haskell.yml
- cabal.project.debug
- cabal.project.release
- lsm-tree.cabal
- test/kmerge-test.hs
I added support for the new GHC-9.12 based on the current alpha release version. The only changes required were the bumping of version bounds and relaxing upper bound constrains on the `base` package in the project's direct and transitive dependencies.
> Adding support for GHC-9.12 based on the alpha release

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Index/Compact.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Index.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/ChecksumHandle.hs
- src/Database/LSMTree/Internal/Index.hs
- src/Database/LSMTree/Internal/Index/Compact.hs
- src/Database/LSMTree/Internal/Index/CompactAcc.hs
- src/Database/LSMTree/Internal/Index/Ordinary.hs
- src/Database/LSMTree/Internal/Index/OrdinaryAcc.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- src/Database/LSMTree/Internal/RunReader.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Index/Compact.hs
- test/Test/Database/LSMTree/Internal/Index/Ordinary.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
- test/Test/Database/LSMTree/Internal/Vector.hs
This pull request introduces type classes that provide a common interface to different types of indexes and their accumulators and instantiates these type classes for the compact and the ordinary index.
> Introduce classes for indexes and their accumulators

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- test/Test/Database/LSMTree/Normal/StateMachine.hs
- test/Test/Database/LSMTree/Normal/StateMachine/DL.hs
The `NoThunks` assertions are re-enabled, but in cases where I expect failures related to `StrictMVar`s, we ignore the thunk and keep checking further into the `MVar` contents.
This is arguably better than not checking `NoThunks` at all, though still unfortunate.
> Re-enable NoThunks tests (#444) 

- src-extras/Database/LSMTree/Extras/Generators.hs
This PR removes the superfluous (and incorrect) Arbitrary instance for WriteBuffer.
> Remove Arbitrary instance for WriteBuffer

- bench/macro/lsm-tree-bench-wp8.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/PageAcc.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class/Common.hs
- test/Database/LSMTree/Class/Normal.hs
- test/Database/LSMTree/Model/IO/Normal.hs
- test/Database/LSMTree/Model/Session.hs
- test/Database/LSMTree/Model/Table.hs
- test/Test/Database/LSMTree/Class/Normal.hs
- test/Test/Database/LSMTree/Internal/Entry.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/Op.hs
- test/Test/Util/Orphans.hs
- test/Test/Util/TypeFamilyWrappers.hs
Follow-up to #469. It's a rather pervasive change, so I'm keeping this PR in draft mode until more important PRs have landed on `main`
> Rename `blob` and `blobref` type variables to `b`

- src/Database/LSMTree/Internal/ChecksumHandle.hs
- src/Database/LSMTree/Internal/Index.hs
- src/Database/LSMTree/Internal/Index/Compact.hs
- src/Database/LSMTree/Internal/Index/Ordinary.hs
- src/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/Index/Compact.hs
Generation of headers and footers of serialized indexes has so far been working only for compact indexes. This pull request introduces an implementation of this functionality for ordinary indexes and extends the `Index` type class such that header and footer generation can be accessed independently of the concrete index type.
As a side change, this pull request also corrects the naming of `postVersionBytes`, an entity local to the `fromSBS` definition for `IndexOrdinary`, to `postTypeAndVersionBytes`.
> Make `headerLBS` and `finalLBS` index-type-polymorphic

- src/Database/LSMTree.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class.hs
- test/Database/LSMTree/Model/IO.hs
- test/Database/LSMTree/Model/Session.hs
- test/Database/LSMTree/Model/Table.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/UnitTests.hs
n-way table unions should be more performant than repeated 2-way unions
> Add n-way table unions

- src-control/Control/RefCount.hs
@dcoutts This PR defines a `HasCallStackIfDebug` macro which
```c
#ifdef NO_IGNORE_ASSERTS
#define HasCallStackIfDebug HasCallStack
#else
#define HasCallStackIfDebug ()
#endif
```
which does not throw a warning when used as
```hs
newRef ::
(RefCounted obj, FinaliserM obj ~ m, PrimMonad m)
=> HasCallStackIfDebug
=> m ()
-> (RefCounter m -> obj)
-> m (Ref obj)
```
but is closer to Haskell syntax than the previous `HAS_CALL_STACK` macro.
> refcount: define macro-constraint `HasCallStackIfDebug`

- lsm-tree.cabal
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Util/Arbitrary.hs
I wrote these commits when I was debugging a looping shrinker, but it turned out it was not the shrinkers for metadata that was looping. It was the shrinker for the  `Errors` type instead (see [fs-sim#84](https://github.com/input-output-hk/fs-sim/pull/84)). So even though the new tests in this PR did not find any bugs, we might as well include the tests on `main`
> Test generators and shrinkers for snapshot metadata

- src-control/Control/RefCount.hs
- src/Database/LSMTree/Internal/BlobFile.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- test-control/Test/Control/RefCount.hs
@dcoutts As per my message, this enables SPECIALISE for the reference counting functions, since it eliminates the need for a `FinaliserM obj ~ m` constraint.
> Use functional dependencies rather than type families to enable SPECIALISE

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
It is one of the core abstractions of the code base. This will allow us to use MergingRun in other modules without having to depend on the whole `MergeSchedule`.
I also untangled its usage a bit to provide a clean module interface. For some of the later changes, there are many alternative solutions, so I added them as separate commits that can be better viewed and discussed individually.
> Split out module MergingRun

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class.hs
- test/Database/LSMTree/Model/IO.hs
- test/Database/LSMTree/Model/Session.hs
- test/Database/LSMTree/Model/Table.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/UnitTests.hs
We add a new `unions` function to the `Internal` module, which should eventually contain the full implementation of unions. For now, the function contains boilerplate for:
* Checking that all input tables have the same configuration, and
* Checking that all input tables are in the same session, and
* Duplicating references to the table contents for each of the tables
* Creating a new table with unioned table contents
The unioning of table contents is not yet implemented and will follow in some later set of PRs.
> Boilerplate for the implementation of n-way unions

- lsm-tree.cabal
- src-control/Control/ActionRegistry.hs
- src/Database/LSMTree/Internal.hs
I've reworked the `TempRegistry` implementation a bit, and I've renamed it to `ActionRegistry` to better reflect that it is a registry of monadic actions. The `ActionRegistry` is introduced in a new module so that the `TempRegistry` can largely remain in use, which makes the diff of this PR smaller. The intent is to replace every use of `TempRegistry` by `ActionRegistry` eventually, probably in a few follow-up PRs. For now, there are two places where we do the replacement already: `openSession` and `closeSession`. I've also taken the liberty to revisit `openSession` and `closeSession` a bit to make them more exception safe
> Add `ActionRegistry` replacement for `TempRegistry`

- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Snapshot.hs
As part of the changes to the scheduled merges prototype to introduce table unions, this refactoring was done. This is because the merging run gets reused in tree merges, where the merging policy makes no sense. So we move it up one level into something that's specific to the levels (the incomming run).
So this is the corresponding refactoring as in the prototype, and is preparation for introducing table unions.
> Move MergePolicyForLevel from MergingRun to IncomingRun

- doc/format-directory.md
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/BlobFile.hs
- src/Database/LSMTree/Internal/Entry.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/RunReader.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Internal/WriteBufferReader.hs
- src/Database/LSMTree/Internal/WriteBufferWriter.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Model/Session.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
This is a WIP PR that serialises the write buffer when creating a snapshot.
I'd love some feedback :)
> Persist write buffer when creating a snapshot

- src-control/Control/RefCount.hs
Otherwise the call stacks will not be properly propagated
> Add missing `HasCallStackIfDebug` pragmas in `Ref` specialisations

- src-control/Control/Concurrent/Class/MonadSTM/RWVar.hs
- test-control/Test/Control/Concurrent/Class/MonadSTM/RWVar.hs
`retry` is interruptible, which can leave the `RWVar` in a state that is unrecoverable.
Kudos to @jasagredo for finding this subtle bug!
> Fix a race condition in `RWVar`

- src-control/Control/RefCount.hs
- test-control/Test/Control/RefCount.hs
In debug mode if the finaliser of a reference counted object throws an error, then the `RefTracker` is never released. `checkForgottenRefs` will then report the reference as forgotten, even though the finaliser ran, though not successfully.  This PR ensures that the `RefTracker` is released even if the finaliser throw an error. This improves the experience of debugging finalisers that fail.
> Release a `RefTracker` even if the corresponding finaliser threw an error

- lsm-tree.cabal
- src-control/Control/ActionRegistry.hs
- test-control/Main.hs
- test-control/Test/Control/ActionRegistry.hs
- test-control/Test/Control/RefCount.hs
This is useful for debugging purposes. See the commit messages.
> Include debug call stacks in `ActionRegistry` errors 

- cabal.project.release
- lsm-tree.cabal
- test/Database/LSMTree/Model/Session.hs
- test/Main.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/FS.hs
- test/Test/Util/FS.hs
See the commit messages for an explanation of the changes.
Currently, we only add fault injection to the `CreateSnapshot` and `OpenSnapshot` actions. This can be extended to other actions, but it would require even more infrastructure. For now, the snapshot functions are the main focus, because we want to test that corruption/disk faults are handled properly.
> Add fault testing to the `StateMachine` tests

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/RunNumber.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- src/Database/LSMTree/Internal/UniqCounter.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
Updating the mutable pointer type of `UniqCounter` to be a `PrimVar` rather than a `StrictMVar`.
> Resolving TODO: PrimVar for UniqCounter

- src/Database/LSMTree/Internal/Entry.hs
A small refactoring addressing the TODO task of converting the `NumEntries` representation to `Word64`. 
This had some implications for serialization of both `Index` types. The round-trip test cases are passing so delicate part of the conversion ought to be correctly handled by the PR.
> Resolving TODO: Converted NumEntries to Word64 representation

- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
A small refactoring addressing the TODO task of converting the `FilePointer` representation to `Word`, while exposing a `Word64` API.
The implementation in the PR replicates the definition of [`Data.Primitive.PrimVar.fetchAddInt`](https://hackage.haskell.org/package/primitive-0.9.0.0/docs/Data-Primitive-PrimVar.html#v:fetchAddInt), adapted for the unsigned `Word` type.
> Resolving TODO: Converted FilePointer to Word representation

- test/Database/LSMTree/Class.hs
- test/Test/Database/LSMTree/Class.hs
`hdl` identifiers are an artifact from the time that `Table` was called `TableHandle`
> Rename `hdl` to `tbl`

- cabal.project.release
This is useful for debugging test failures in the presence of disk faults.
> `s-r-p` for `quickcheck-lockstep` with more verbose counterexamples

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- test/Test/Database/LSMTree/Internal/PageAcc.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Util/QLS.hs
> QLS: check `NoThunks` only at the end of an action sequence

- src-control/Control/ActionRegistry.hs
- test/Test/Database/LSMTree/StateMachine.hs
> QLS: catch missed disk fault errors

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
> Rename Merge.Level to MergeType and extend with MergeUnion enum value

- lsm-tree.cabal
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/WriteBufferBlobs/FS.hs
> Make `WriteBufferBlobs` functions exception safe

- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTest.hs
- prototypes/ScheduledMergesTestQLS.hs
Tests pass, but still needs a bit of cleaning up, additional invariants and proper tracing. The lookups are currently quite naive and inefficient.
> Table union support in prototype

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
Some micro benchmarks don't run any more. I fixed two where the benchmark environment code got broken by recent changes.
Fixes #440. (this was one of them)
> Fix micro benchmarks

- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
Move checkCRC to the CRC32C module to allow reuse in validating the write buffer files.
@mheinzel reopening as PR into main.
> fix: move checkCRC to CRC32C

- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
Move FileFormatError to Paths module to allow reuse in validating the write buffer files.
> fix: move FileFormatError to Paths

- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
- test/Test/FS.hs
- test/Test/Util/FS.hs
A next step would be to apply the same explicit corruption method to the statemachine tests.
In parallel, we can add silent corruption to `fs-sim`, which currently only simulates noisy corruption. We could use this silent corruption simulation to eventually replace the explicit `flipFileBit` calls
> Test snapshot corruption

- prototypes/ScheduledMerges.hs
Based on #477, which needs to be merged first.
This statically enforces that merging runs in different parts of the LSM can only have specific merge types.
Note the individual commits. There are multiple possible ways of going from the individual merge types to how the merge is performed. Two are shown here.
> Add type parameter to merging runs in prototype

- test/Test/FS.hs
- test/Test/Util/FS.hs
> Fix out-of-bounds array access in `hFlipBit`.

- test/Test/Database/LSMTree/StateMachine.hs
WIP: This handler does not appear to catch any `FileFormatError`.
> test: add handler for FileFormatError to StateMachine

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
The intention is to simplify things and make them more obviously correct
in the presence of concurrency. This should have the bonus of making it
easier to reliably determine leftover/excess supplied credits (which is
something we want for supplying credits to trees of merging runs).
The approach is to change the counters from three independent counters,
to just two, which are modified together as a pair atomically.
Previously we tracked the credits spent and unspent, and the steps
performed. We did not explicitly keep track of credits that were in the
process of being spent.
Now we track spent and unspent (and not steps performed), but the spent
credits includes those that are in the process of being spent. We keep
these together in a single atomic variable, and so all operations on the …
> New merging run credit counter strategy using an atomic pair of counters

- lsm-tree.cabal
- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTest.hs
Best reviewed commit by commit.
Fixes #550. Also does some refactoring. The new test catches the issue reliably, but requires a lot of boilerplate, with the definition of a new type. It might be possible to reduce that somewhat, e.g. by unifying the `MTree` and `T` datatype, but it's not clear that's worthwhile.
The final commit was part of an attempt to improve the situation, but currently is not really needed. It might still be a good direction to go in, allowing to handle invariant violations in a pure manner, instead of through exceptions. Should I keep it?
> Fix prototype issue with non-normalised, but structurally empty merging trees

- blockio-api/src/System/FS/BlockIO/API.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- test/Test/Database/LSMTree/Internal/Run.hs
Not all the snapshot directory contents were being synchronised, and arguably not in the correct order. The synchronisation now only happens at the very end of taking a snapshot. Because of this, if other parts of the `createSnapshot` function fail, then we won't have flushed file and directory contents to disk unnecessarily.
> Bugfix: synchronise the snapshot directory and its contents

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/MergingRun.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
More porting of changes for table union from the prototype into the implementation: when supplying credits to a MergingRun we want to return the leftover/unused credits. This is needed because supplying of credits to a union merge will require that all credits get spent, but union merges are made up of many ongoing merging runs.
This turns out to be more tricky than at first appearance. The existing strategy for tracking credits (unspent, spent and merge steps performed) made it very difficult to figure out how to account leftover credits.
So the major change in this PR is to change the MergingRun credit tracking strategy
The intention is to simplify things and make them more obviously correct in the presence of concurrency. This also make it easier to reliably determine leftover/excess …
> Table union porting: change merge credit tracking strategy and return leftovers

- .github/dependabot.yml
Dependabot will automatically open PRs if some dependencies in the GHA workflow files need updating.
> Enable version updates for GitHub Actions using Dependabot

- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
The credit scaling for levelling vs teiring use different formulas. The implementation's version of this scaling had the two cases swapped. This will have resulted in supplying too few credits to levelling runs (and thus having to complete too much at the end) and too many to teiring runs (thus completing too early). In both cases it will have resulted in IO not being spread out evenly, and thus higher peak latency for updates.
We can now successfully assert that upon expecting a merging run to be complete we have supplied credits equalling the total debt. Previously this assertion failed, which led to the discovery of the bug.
We need to find a test to ensure we are spreading out merging work and not supplying too many credits. We supply credits for the worst case, which currently means …
> The credit scaling in the impl was backwards from the prototype

- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTest.hs
Previously we've had a somewhat complex method to scale credits from
those supplied in a level (1 per update) to the credits used in merging.
The existing scheme has a number of downsides:
* no clear distinction between scaled and unscaled credits, what does
each one measure?
* complex, needs scaling dependent of the merge-policy
* always uses worst case supply of credits so often finishes early
* rounding errors compound problem of credit over-supply
* no satisfactory way to check we do not over-supply credits
* contributing credits to a merge from multiple handles will cause the
merge to finish earlier than any of the handles needs it to finish,
thus doing work more eagerly than necessary.
The new scheme involves:
* distinguishing physical vs nominal credits, with a clear definition
for …
> Prototype: change credit scaling, using nominal vs physical credit

- test/Test/Database/LSMTree/Internal/Index/Ordinary.hs
There are several comments that document private variables in `Test.Database.LSMTree.Internal.Index.Ordinary`. Currently, these comments are ordinary comments, but it makes sense to turn them into Haddock comments, for the following reasons:
* It is possible to prompt Haddock to include private entities into generated documentation.
* A comment being a Haddock comment makes it clear that it contains interface documentation and not just a remark or such.
* In other situations, such comments may contain Haddock markup already.
> Turn private API documentation into Haddock comments

- src-control/Control/RefCount.hs
I'll use this in tests I'm writing, where I want ignore the references. In the context of that test, forgotten references are allowed
> Add `ignoreForgottenRefs`

- src/Database/LSMTree/Internal/Index.hs
- src/Database/LSMTree/Internal/Index/Compact.hs
- src/Database/LSMTree/Internal/Index/Ordinary.hs
Currently, the documentation of the general index interface requires serialized keys to satisfy the key size constraints of compact and ordinary indexes. This pull request changes the documentation such that it requires only the key size constraint of the actually used index type to be satisfied.
> Loosen the size constraints on serialized keys

- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
Follow-up to https://github.com/IntersectMBO/lsm-tree/pull/573#discussion_r1956126412
This makes `MergingRun`'s `t` parameter not just phantom, but actually stores the merge type as `:: t` internally. As a result, we also have to move the `IsMergeType` class further up in the module hierarchy.
> Propagate MergingRun's type parameter to Merge

- blockio-api/src/System/FS/BlockIO/API.hs
- cabal.project.release
- test/Test/Database/LSMTree/Internal/BlobFile/FS.hs
- test/Test/Database/LSMTree/Internal/WriteBufferBlobs/FS.hs
- test/Test/Util/FS.hs
In the updated dependency, a bug in `hGetBufExaclty` and `hGetBufExactlyAt` is fixed.
> Update fs-sim dependency

- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/RunNumber.hs
Use stock derived show for newtypes RunNumber, TableId and CursorId, rather than newtype derived. This means they get rendered as "RunNumber 3" rather than 3. This makes traces easier to read. It also means when things are shown in errors or ghci output, the result can be pasted back in again as valid syntax.
Carefully checked that show was not being used for anything other than derived show for other types, so we don't change the rendering of anything important. Did this by temporarily removing the show instance entirely and looking for build errors. Fixed two such cases in file path rendering.
> Improve readability of numbers in traces and errors

- src-control/Control/RefCount.hs
- test/Test/Database/LSMTree/StateMachine.hs
Make sure the forgotten refs state is reset reliably after each run, so that during shrinking we do not get false errors from previous runs causing us to produce nonsense shrunk test cases.
> Improve the reliability of forgotten refs checking in the state machine tests

- test/Test/Database/LSMTree/StateMachine.hs
This gives us reasonable shrunk test sizes if you happen to hit mupserts, and also helps considerably with multi-way unions.
> In the state machine tests, shrink mupserts and table unions

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/MergingRun.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec/Golden.hs
This is the equivalent of #571 but for the real implementation. There's quite a few small refactoring steps.
Previously we would scale each contribution of credits by scaling the
credit delta, rounded up. The scaling itself also depended on the
merging policy. The scaling was done to to work for the worst case size
of merge input runs, irrespective of the acutal input run sizes.
This approach would supply more credit than needed (thus finishing the
merge unnecessarily early) for two reasons: 1. assuming worst case
number of input runs and run sizes and 2 accumulation of rounding
errors over a sequence of small credit contributions. The approach also
meant that credit contributions to the same merge from different tables
would cause credit over-supply, and finishing the merge earlier than …
> Change credit scaling, using nominal vs merge credit

- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
Instead of adding `Maybe Errors` to each constructor, which would probably lead to quite a bit of duplicated code, I opted to add a single top-level constructor that contains a `Maybe Errors` and an `Action'`. This `Action'` is a new data type that contains the interesting constructors, like `New` and `Updates`.
As a result of this change, there quite a few mechanical changes, but not much of it is interesting. However, having made this change, we are now ready to enable fault injection for all the actions whenever we want to.
> QLS: give all actions errors

- src-control/Control/RefCount.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- test-control/Test/Control/RefCount.hs
`RefException`s are currently thrown from `IO`, but we can not catch these exceptions in `IOSim`. This PR makes changes to ensure we can catch (almost all) exceptions in any monad that has the right constraints. The only exceptions we still can't catch outside of `IO` are exceptions thrown by the `DeRef` pattern.
> Make `RefException`s `catch`able in `IOSim`

- prototypes/ScheduledMerges.hs
- prototypes/ScheduledMergesTest.hs
- prototypes/ScheduledMergesTestQLS.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
The implementation is left open for now. I'll follow up this PR with a PR to add test support for union debt/supply.
> Public API: add union debt/credits types and related functions

- .hlint.yaml
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/MergingRunData.hs
- src-extras/Database/LSMTree/Extras/MergingTreeData.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Util/Arbitrary.hs
Similarly to the existing `RunData`, these are simplified versions of `MergingRun` and `MergingTree`, which can be generated, shrunk and turned into their full on-disk versions.
I also added labelling and tests for the generators and shrinkers, as well as the code creating the `MergingTree` etc. from the data.
The tests are quite slow even after halving the maximum size. The main issue is that `RunData` has a lot of possible shrinks (sometimes over 100k), which gets even worse when there are dozens of them in the tree.
<details>
<summary>test output</summary>
```
Test.Database.LSMTree.Generators
RunData
Arbitrary satisfies invariant:          OK (0.60s)
+++ OK, passed 100 tests.
run has large k/ops (100 in total):
52% has large k/op
48% no large k/op
run length (100 in total):
68% 10 <= n …
```
> Introduce MergingRunData and MergingTreeData

- src/Database/LSMTree/Internal/Index/OrdinaryAcc.hs
- src/Database/LSMTree/Internal/Vector/Growing.hs
This pull request adds assertions that guarantee that minimum keys used in the construction of ordinary indexes fulfill necessary conditions.
This addition is important because we plan to change the tests of higher-level modules to use ordinary indexes instead of compact ones. After this change, these tests wouldn’t catch passing of bogus minimum keys anymore without the extra assertions of this pull request, since minimum keys are ignored when building ordinary indexes.
> Add assertions about keys to ordinary-index construction

- lsm-tree.cabal
- src-control/Control/RefCount.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
- test/Test/Util/FS/Error.hs
This PR adds
* Functionality to log errors injected by `fs-sim`
* Assertions in the state machine to check that always see disk errors if we inject *noisy* errors through `fs-sim`. That is, the assertion checks that no noisy errors are swallowed.
* Finally, we add and test a dynamic logic (`DL`) formula that injects errors into *all* `lsm-tree` actions and runs the swallow error assertion afterwards.
> QLS: test that we do not swallow exceptions

- lsm-tree.cabal
- prototypes/ScheduledMerges.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
- test/Test/Database/LSMTree/Internal/MergingTree.hs
There are a few TODOs that can still be improved, but doesn't necessarily have to be in this PR.
The last commit should still be dropped (in favour of #611), but shows that the lockstep tests pass with unions enabled.
> Lookups in merging tree

- bench/micro/Bench/Database/LSMTree/Internal/Index.hs
- bench/micro/Main.hs
- lsm-tree.cabal
- src/Database/LSMTree/Internal/Index/Ordinary.hs
- src/Database/LSMTree/Internal/Vector.hs
This pull request adds index benchmarks that are independent of index type and instantiates them for compact and ordinary indexes.
> Add general index benchmarks

- src/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/UnitTests.hs
This PR renames `ErrSnapshotNotExists` to `ErrSnapshotDoesNotExist` for consistency.
> fix: rename ErrSnapshotNotExists to ErrSnapshotDoesNotExist

- bench/micro/Bench/Database/LSMTree/Normal.hs
- src-extras/Database/LSMTree/Extras/Orphans.hs
- src-extras/Database/LSMTree/Extras/UTxO.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- test/Test/Database/LSMTree/Internal/Serialise/Class.hs
This PR removes the unused method `deserialiseValueN`.
> fix: remove unused `deserialiseValueN`

- test/Test/Database/LSMTree/Internal/Index/Compact.hs
Use prop_arbitraryAndShrinkPreserveInvariant rather than the naive version (which no doubt pre-dates the handy util).
On my machine with an unoptimised build, improves running time from 50s to 17s.
> Faster shrinker test for Compat's Chunks generator

- .github/workflows/documentation.yml
- .github/workflows/haskell.yml
This PR removes the uses of `fail-fast: false` without a strategy.
> fix(ci): remove erroneous uses of fail-fast

- bench/macro/lsm-tree-bench-wp8.hs
- bench/micro/Bench/Database/LSMTree/Monoidal.hs
- bench/micro/Bench/Database/LSMTree/Normal.hs
- src/Database/LSMTree/Internal/Config.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec/Golden.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
Up to now, `defaultTableConfig` declared compact indexes to be used by default. This pull request changes this, making ordinary indexes the default.
Furthermore, this pull request changes the following files such that they now override the `confFencePointerIndex` field of `defaultTableConfig` with `CompactIndex` in order to continue using compact indexes:
* `bench/macro/lsm-tree-bench-wp8.hs`
* `bench/micro/Bench/Database/LSMTree/Monoidal.hs`
* `bench/micro/Bench/Database/LSMTree/Normal.hs`
* `test/Test/Database/LSMTree/Internal/Snapshot/Codec/Golden.hs`
* `test/Test/Database/LSMTree/Internal/Snapshot/FS.hs`
* `test/Test/Database/LSMTree/UnitTests.hs`
The remaining source code files that use `defaultTableConfig` are the following ones:
* `test/Test/Database/LSMTree/Class.hs`
* …
> Make ordinary indexes the default

- src/Database/LSMTree/Internal.hs
The previous docs were misaligned with their respective constructors.
> fix: LSMTreeError docs

- test/Test/Database/LSMTree/Internal/Vector.hs
This pull request cleans up the import list of `Test.Database.LSMTree.Internal.Vector`.
> Clean up `Test.Database.LSMTree.Internal.Vector` imports

- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- test/Database/LSMTree/Model/Session.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/UnitTests.hs
Should go on top of #608 and #609. We should also add some union-related labelling.
> Enable unions in lockstep tests

- bench/micro/Bench/Database/LSMTree/Internal/Index.hs
- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal/Index.hs
- src/Database/LSMTree/Internal/Index/Ordinary.hs
- src/Database/LSMTree/Internal/Vector/Growing.hs
- test/Test/Database/LSMTree/Class.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec/Golden.hs
- test/Test/Database/LSMTree/StateMachine.hs
Enabling both types of tests for both types of indexes unearthed some `NoThunks` failures and a subtle assertion failure. Both are fixed now, though the assertion failure currently has a workaround instead of a proper fix.
> Run `Class`-based and `StateMachine` tests using both index types

- lsm-tree.cabal
- src/Database/LSMTree/Internal/RunAcc.hs
- test/Main.hs
- test/Test/Database/LSMTree/Internal/Monkey.hs
- test/Test/Database/LSMTree/Internal/RunBloomFilterAlloc.hs
These tests were missing a link with the real implementation, since we were testing bloom filter construction functions that were not used in the real implementation. The updated tests test the `RunAcc`'s method of bloom filter allocation directly.
> Update bloom filter FPR tests

- bench/macro/lsm-tree-bench-wp8.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
- test/Test/Database/LSMTree/StateMachine.hs
Perhaps tellingly, every single use save one used either `fromJust` or `maybe (error ...)`. The only use that handled the error simply didn't run any tests if the function returned maybe.
> fix: replace mkSnapshotName that returns Maybe with toSnapshotName that errors

- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- src-extras/Database/LSMTree/Extras/MergingRunData.hs
- src-extras/Database/LSMTree/Extras/MergingTreeData.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/MergingTree.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
This pull request removes `defaultRunParams` in favor of explicit specification of run parameters.
> Make run parameters explicit

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Index.hs
- prototypes/ScheduledMerges.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
- src/Database/LSMTree/Internal/Run.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Test/Database/LSMTree/Class.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/MergingRun.hs
- test/Test/Database/LSMTree/Internal/MergingTree.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/StateMachine.hs
There is an issue in the lockstep tests with how `SupplyPortionOfDebt` works, so I had to disable that action for now. I'll see if we can salvage it, but we'd probably have to relax the `Eq (Obs h a)` instance for `UnionCredits`. Ideally we'd have separate cases for `SupplyUnionCredits` and `SupplyPortionOfDebt` to enforce that for one the implementation can't return fewer and for the other it can't return more leftovers than the model.
I'm also still adding a property based test for supplying into the `MergingTree`.
> Implement remainingUnionDebt and supplyUnionCredits

- src-extras/Database/LSMTree/Extras/Generators.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
- test/Test/Database/LSMTree/Internal/Run.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
- test/Test/Database/LSMTree/Internal/RunBuilder.hs
- test/Test/Database/LSMTree/Internal/RunReader.hs
- test/Test/Database/LSMTree/Internal/RunReaders.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
- test/Test/Database/LSMTree/UnitTests.hs
This pull request changes the tests of various index-using modules such that these tests now use ordinary indexes instead of compact ones. #619 already made such changes to certain test modules that refer to the default table configuration. The present pull request changes test modules that specify the index type in isolation, that is, not as part of a table configuration. It modifies all such modules except for the snapshot-related ones and the main one of the state-machine-related ones.
> Finish switching of index-using tests to ordinary indexes

- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Range.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/Op.hs
I perused comments about TODOs and found some things that we can probably remove or simplify
> Remove some obsolete TODOs and unused declarations

- src/Database/LSMTree/Common.hs
- test/Test/Util/Orphans.hs
Slightly nicer for users of the public API, so that they can just use `io-classes` constraints in their library instead of propagating `IOLike` everywhere.
> Make `IOLike` a type synonym instead of a class

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/MergingTree.hs
Follow-ups to feedback in #609 and #633.
The test output for `prop_supplyCredits` now is:
```
Test.Database.LSMTree.Internal.MergingTree
prop_supplyCredits: OK (10.59s)
+++ OK, passed 100 tests:
73% completed
10% trivial
supplied credits (853 in total):
82.8% 10 <= n < 100
17.2% 1 <= n < 10
```
> Small improvements related to table unions

- src/Database/LSMTree.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Model/Session.hs
- test/Test/Database/LSMTree/StateMachine.hs
This PR renames the `TableNotCompatbleError` to `TableUnionNotCompatibleError` and adds more information.
> fix: restructure TableNotCompatibleError to TableUnionNotCompatibleError

- src/Database/LSMTree/Internal/Index/Ordinary.hs
- src/Database/LSMTree/Internal/Index/OrdinaryAcc.hs
- test/Test/Database/LSMTree/Internal/Index/Ordinary.hs
Previously, the keys stored in ordinary indexes and ordinary-index accumulators were of type `SerialisedKey`, and the append operations for ordinary-index accumulators did not truncate keys that were represented as slices of larger byte sequences to their actual payloads. This pull request changes `IndexOrdinary` and `IndexOrdinaryAcc` to use `Unsliced SerialisedKey` for storing keys, so that it is guaranteed that only actual key contents are stored.
> Make ordinary indexes store their keys unsliced

- bench/macro/lsm-tree-bench-wp8.hs
- lsm-tree.cabal
- src/Database/LSMTree.hs
- src/Database/LSMTree/Common.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Config/Override.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Monoidal.hs
- src/Database/LSMTree/Normal.hs
- test/Database/LSMTree/Class.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
- test/Test/Database/LSMTree/UnitTests.hs
Since #608, using a `TableConfigOverride` when opening a snapshot has no effect. This commit restores the feature that we can change the disk cache policy on snapshot open.
Internally, instead of threading through a modified config to open the snapshot, we modify the whole `SnapshotMetaData` (replacing the disk cache policy everywhere) and open the snapshot from that modified metadata.
A first idea we had was to modify a table config while its table is live, but there are some challenges. Changing a table config when the table is offline seems to be more straightforward, so that's the approach we took (for now). An explanation of the challenges can be found in the `*.Config.Override` module.
> Allow overriding the disk cache policy (feature restored)

- .hlint.yaml
- bench/micro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- bench/micro/Bench/Database/LSMTree/Internal/Index/Compact.hs
- blockio-api/test/Main.hs
- bloomfilter/examples/Words.hs
- bloomfilter/src/Data/BloomFilter/BitVec64.hs
- bloomfilter/src/Data/BloomFilter/Internal.hs
- bloomfilter/tests/bloomfilter-tests.hs
- scripts/lint-hlint.sh
- src-extras/Database/LSMTree/Extras/Generators.hs
- src-extras/Database/LSMTree/Extras/MergingTreeData.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src-extras/Database/LSMTree/Extras/UTxO.hs
- src/Database/LSMTree/Internal/BlobRef.hs
- src/Database/LSMTree/Internal/RawBytes.hs
- src/Database/LSMTree/Internal/RunAcc.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- test/Test/Database/LSMTree/Internal/CRC32C.hs
- test/Test/Database/LSMTree/Internal/Index/Compact.hs
- test/Test/Database/LSMTree/Internal/RawBytes.hs
- test/Test/Database/LSMTree/UnitTests.hs
- test/Test/Util/FS.hs
Also, clean up HLINT pragmas by replacing them with `ignore` entries in the `.hlint.yaml`.
> Use `hlint` on every Haskell file

- src-extras/Database/LSMTree/Extras/NoThunks.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
- test/Test/Database/LSMTree/Internal/MergingTree.hs
- test/Test/Database/LSMTree/UnitTests.hs
This avoids having to rebuild it and most importantly keeps blob references from becoming invalidated.
> Cache lookup tree for the union level

- .github/actions/setup-cabal-docspec/action.yaml
- .github/workflows/ci.yml
- lsm-tree.cabal
- scripts/test-cabal-docspec.sh
`cabal-3.10` has a bug in `cabal haddock-project`, which leads to bad hyperlinks in our published haddocks
Also: my editor automatically removed trailing whitespace in the workflow file
> GHA: use `cabal-3.12`

- bench/macro/lsm-tree-bench-lookups.hs
- bench/micro/Bench/Database/LSMTree/Internal/Merge.hs
- bench/micro/Bench/Database/LSMTree/Internal/WriteBuffer.hs
- src-extras/Database/LSMTree/Extras/MergingRunData.hs
- src-extras/Database/LSMTree/Extras/MergingTreeData.hs
- src-extras/Database/LSMTree/Extras/RunData.hs
- src/Database/LSMTree/Internal.hs
- src/Database/LSMTree/Internal/Cursor.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Merge.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- src/Database/LSMTree/Internal/MergingTree.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
- src/Database/LSMTree/Internal/Serialise.hs
- src/Database/LSMTree/Internal/Snapshot.hs
- src/Database/LSMTree/Internal/WriteBuffer.hs
- src/Database/LSMTree/Internal/WriteBufferBlobs.hs
- src/Database/LSMTree/Internal/WriteBufferReader.hs
- test/Test/Database/LSMTree/Internal/Merge.hs
We re-defined the `ResolveSerialisedValue` type synonym in a few places, sometimes with a different name. Moving it to `Internal.Serialise` allows us to simply import it wherever we want to use it. This is done in preparation for making cursors support merging trees.
> Consistently use type ResolveSerialisedValue, avoid mappend terminology

- bloomfilter/src/Data/BloomFilter.hs
- bloomfilter/src/Data/BloomFilter/Easy.hs
- bloomfilter/src/Data/BloomFilter/Hash.hs
- src-kmerge/KMerge/Heap.hs
- src-kmerge/KMerge/LoserTree.hs
- src/Database/LSMTree/Internal/Arena.hs
- src/Database/LSMTree/Internal/Lookup.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- src/Database/LSMTree/Internal/WriteBufferWriter.hs
This pull request changes the American-style pragma name `SPECIALIZE` to the equivalent British-style pragma name `SPECIALISE`.
> Change `SPECIALIZE` to `SPECIALISE`

- src/Database/LSMTree/Internal/Arena.hs
- src/Database/LSMTree/Internal/CRC32C.hs
- src/Database/LSMTree/Internal/IncomingRun.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingTree.hs
- src/Database/LSMTree/Internal/MergingTree/Lookup.hs
This pull request adds missing `IO` specializations and, in `Database.LSMTree.Internal.Arena`, where `ST` specializations are generally present as well, also missing `ST` specializations.
> Add missing `IO` and `ST` specializations

- bench/macro/lsm-tree-bench-wp8.hs
- bench/micro/Bench/Database/LSMTree.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/IncomingRun.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/Snapshot/Codec.hs
- src/Database/LSMTree/Internal/Unsafe.hs
- test/Test/Database/LSMTree/Internal.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec.hs
- test/Test/Database/LSMTree/Internal/Snapshot/Codec/Golden.hs
- test/Test/Database/LSMTree/Internal/Snapshot/FS.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
- test/Test/Database/LSMTree/UnitTests.hs
In the public API it is only used inside the `AllocWriteBuffer` config option. It is mostly inconvenient that a user has to wrap an `Int` in a `NumEntries`, and there are no clear benefits from the newtype.
`NumEntries` is probably still useful as an internal newtype to ensure some type safety, and to serve as documentation, so I kept it in the library internals.
> Do not expose `NumEntries` from the public API

- .github/workflows/ci.yml
- cabal.project.release
- lsm-tree.cabal
- scripts/generate-readme.hs
- src-control/Control/RefCount.hs
- src/Database/LSMTree/Internal/BloomFilterQuery1.hs
- src/Database/LSMTree/Internal/ByteString.hs
- src/Database/LSMTree/Internal/IncomingRun.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/MergingRun.hs
- xxhash/src/XXH3.hs
Recently, `cardano-node` releases have started using `ghc-9.6` instead of `ghc-8.10`. Dropping support for `ghc-8.10` in `lsm-tree` makes our lives a bit easier, because we can use less conditional compilation in our codebase. We'll now support versions `ghc-9.2` and up, because we weren't explicitly supporting `ghc-9.0` anyway
> Drop support for `ghc-8.10`

- lsm-tree.cabal
- src-extras/Database/LSMTree/Extras/Orphans.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal/ByteString.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/Primitive.hs
- src/Database/LSMTree/Internal/Serialise/Class.hs
- src/Database/LSMTree/Simple.hs
- test/Test/Database/LSMTree/Internal/Serialise/Class.hs
The intent of this PR is to clean up and improve these classes a bit, since they're now exported from the public API
> Revisit `SerialiseKey` and `SerialiseValue` classes

- src/Database/LSMTree.hs
- src/Database/LSMTree/Simple.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
This enables us to add configuration fields in the future without a breaking change.
> feat: hide TableConfig constructor

- src/Database/LSMTree/Internal/Paths.hs
- src/Database/LSMTree/Internal/Unsafe.hs
This PR renames ErrSnapshotNameInvalid -> ErrInvalidSnapshotName for consistency with other errors.
> rename: ErrSnapshotNameInvalid -> ErrInvalidSnapshotName

- bloomfilter/tests/bloomfilter-tests.hs
It was failing for very large FPR values. This test involves rounding to an integer number of bits (filter size). With a low number of bits (corresponding to high FPRs and small number of elements) the accuracy loss from rounding is significant. So we need looser tolerances in these cases.
> Fix flakey bloomfilter test prop_calc_size_fpr_fpr

- src/Database/LSMTree.hs
- src/Database/LSMTree/Simple.hs
I had some text lying around from a while ago about ACID properties, so I thought it'd be useful to include it in the public API
> Public documentation about ACID properties

- test/Test/Database/LSMTree/Internal/WriteBufferReader/FS.hs
- test/Test/Database/LSMTree/StateMachine.hs
- test/Test/Database/LSMTree/StateMachine/DL.hs
- test/Test/Util/FS.hs
Failure found in https://github.com/IntersectMBO/lsm-tree/actions/runs/15140425104/job/42562757365?pr=683
The test failure can be reproduced using the following seed:
```
cabal run lsm-tree-test -- \
-p '$0=="lsm-tree.Test.Database.LSMTree.StateMachine.propLockstep_RealImpl_MockFS_IO"' \
--quickcheck-replay="(SMGen 11798857835899383018 1561550946174790845,97)"
```
The test fails because an injected error with an `FsReachedEOF` type is
swallowed by the `openTableFromSnapshot` public API function. We fix the test
failure (for now) by not generating errors of that type.
At some point we should think of a more principled approach to this type of
swallowed error. `FsReachedEOF` is not an error type that any of the `HasFS`
primitives can throw in practice when using the real file system, but …
> `StateMachine`: fix a test failure where an injected error is swallowed

- bench/micro/Bench/Database/LSMTree/Internal/BloomFilter.hs
- bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs
- blockio/src-linux/System/FS/BlockIO/Async.hs
- cabal.project.blockio-uring
- src-extras/Database/LSMTree/Extras/Random.hs
And as a bonus, use a random shuffle implementation with a fixed seed in the micro-benchmarks. This should make them a little more reproducible. I made these changes when experimenting with unboxed `IOOp` vectors, but in the end we scrapped unboxed `IOOp` vectors. It's still useful to include
> Bump `s-r-p` for `blockio-uring`

- lsm-tree.cabal
- src-prototypes/ScheduledMerges.hs
- test-prototypes/Main.hs
- test-prototypes/Test/ScheduledMerges/RunSizes.hs
- test-prototypes/Test/ScheduledMergesQLS.hs
We'd need to configure the write buffer size in the `ScheduledMerges` prototype if we want to compare traces for the prototype and real implementation (see #445).
This PR also changes the run size calculations to be somewhat closer to the calculations in the real implementation.
This PR builds on top of #715 to reduce the number of merge conflicts
> `ScheduledMerges`: make the write buffer size configurable

- src-prototypes/ScheduledMerges.hs
- test-prototypes/Test/ScheduledMerges/RunSizes.hs
- test-prototypes/Test/ScheduledMergesQLS.hs
It's probably also a prerequisite to prototype the merge schedule with size ratios other than `4` before we can be confident that we can make it configurable in the real implementation too. 
At that point, we'd need to configure the size ratio in the `ScheduledMerges` prototype if we want to compare traces for the prototype and real implementation (see #445). 
This PR builds on top of #716 to reduce the number of merge conflicts
> `ScheduledMerges`: make the size ratio configurable

- src/Database/LSMTree.hs
- src/Database/LSMTree/Simple.hs
A small correction of a repeatedly occurring phrase about disk I/O complexity.
> Change “this” to “the” for “disk I/O complexity”

- .github/workflows/ci.yml
- scripts/lint-hlint.sh
They're over a year old, so it probably doesn't hurt to set them to a more recent date.
Also: update the `hlint` version
> Update `hackage-index-state`s for GHA lint jobs

- cabal.project.debug
- src/Database/LSMTree/Internal/Unsafe.hs
The `TraceMerge` datatype for trace messages is not very polished, and it exposes quite a few internal datatypes. For now, I think it's best to hide `MergeTrace` from the public API.
We do this using CPP using a macro flag, so that we can still inspect the `MergeTrace` if we want to in development.
One other approach I tried was to create a dedicated trace message datatype for the public API, so that we can map the internal trace types to the public trace types. However, this is quite boilerplatey and also incurs a slight performance cost in allocations. I've also tried type-level tags to differentiate between different severity levels of traces (e.g., debug vs. info), but I'm expecting that to also incur some performance cost.
Since we're planning to change `MergeTrace` at some point …
> Hide `TraceMerge` from the public API unless compiling in debug mode

- src-prototypes/ScheduledMerges.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- test-prototypes/Test/ScheduledMergesQLS.hs
Resolves #755 
The prototype had a bug in the calculation of `maxPhysicalDebt` where it was not
considering that incoming runs that are inputs to a merge can be overfull. Runs
can be overfull because we hold back runs that are underfull. However, runs
should only be overfull in the sense that they are too large for their current
level. They can't be overfull with respect to the next level too.
This same bug occurred in `invariant`, where a similar change was made to
consider overfull runs properly.
Some other minor changes to `invariant` were made to make the checked invariant
a little more precise.
Note that the assertion failures only started appearing on CI runs after #716 and #717 were merged. I realised that it's a relatively rare scenario to create underfull and overfull runs, but …
> `ScheduledMerges`: fix a bug in `maxPhysicalDebt` and `invariant`

- lsm-tree.cabal
- src-prototypes/ScheduledMerges.hs
- test-prototypes/Test/ScheduledMerges.hs
- test-prototypes/Test/ScheduledMerges/RunSizes.hs
- test-prototypes/Test/ScheduledMergesQLS.hs
Builds on top of #763 to prevent merge conflicts
The renamings were some changes I had lying around on an older branch, and the new trace messages I added to troubleshoot #755.
> `ScheduledMerges`: some renaming and new trace messages

- bench/micro/Bench/Database/LSMTree/Internal/Index.hs
- doc/format-run.md
- src-extras/Database/LSMTree/Extras/Generators.hs
- src/Database/LSMTree.hs
- src/Database/LSMTree/Internal/Config.hs
- src/Database/LSMTree/Internal/MergeSchedule.hs
- src/Database/LSMTree/Internal/RawBytes.hs
- src/Database/LSMTree/Simple.hs
- test/Test/Database/LSMTree/Generators.hs
- test/Test/Database/LSMTree/Internal/Index/Compact.hs
- test/Test/Database/LSMTree/Internal/Lookup.hs
- test/Test/Database/LSMTree/Internal/RawBytes.hs
- test/Test/Database/LSMTree/Internal/RunAcc.hs
- test/Test/Database/LSMTree/StateMachine.hs
We make`topBits64` safe for raw bytes of size less than 8. When the size of the raw bytes is less than 8, then a fallback method is used that is likely slower. When the size of the raw bytes is 8 or higher, then an
additional integer comparison is made, but this has very little impact on
performance, which I verified using micro-benchmarks. The upside to making the
function safe for any input raw bytes is that the API and test generators become
simpler, because there is one fewer constraint to satisfy: the minimum size of 8
bytes for serialised keys.
Now that `topBits64` is fully safe, remove the 8-byte key constraint when using
the compact index. Instead, the config option for the index type includes a hint
not to use the compact index if keys are too small, because that will lead
to bad …
> Lift the restriction of minimum 8-byte keys for the compact index

- src/Database/LSMTree.hs
They are hidden behind a debug flag now.
> Remove internal trace types from the public API

- .github/workflows/check-release-builds.yml
Basically, if a release tag of the form `blockio-*`, `bloomfilter-blocked-*` or `lsm-tree-*` is created, the workflow will trigger and it will try to build the corresponding library without the local dev environment. Instead, it will build the library without tests and benchmark with the latest Hackage index-state. This should be a sanity check that the library version will work out of the box once it is released to Hackage
> Add a script that can be used to check release builds
